# 1. Scrape the details of most viewed videos on YouTube from Wikipedia: Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/ 
# You need to find following details:
# A) Rank
# B) Name
# C) Artist
# D) Upload date
# E) Views

In [1]:
import selenium
import pandas as pd
from selenium import webdriver
from bs4 import BeautifulSoup
import requests
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium import webdriver
import os
import urllib
import time

In [2]:
driver = webdriver.Chrome(r"C:\Data Science\Flip Robo\Selenium\chromedriver_win32\chromedriver.exe")

In [3]:
url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)

In [25]:
rank=[]
for i in range(1,31):        
    rank_tag=driver.find_element_by_xpath("/html/body/div[3]/div[3]/div[5]/div[1]/table[3]/tbody/tr[{}]/td[1]".format(i))
    rank.append(rank_tag.text.replace(".",''))

In [26]:
rank

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30']

In [90]:
video_name=[]
for i in range(1,31):        
    video_name_tag=driver.find_element_by_xpath("/html/body/div[3]/div[3]/div[5]/div[1]/table[3]/tbody/tr[{}]/td[2]".format(i))
    video_name.append(video_name_tag.text)

In [91]:
video_name

['"Baby Shark Dance"[22]',
 '"Despacito"[24]',
 '"Johny Johny Yes Papa"[25]',
 '"Shape of You"[26]',
 '"See You Again"[27]',
 '"Masha and the Bear – Recipe for Disaster"[30]',
 '"Bath Song"[31]',
 '"Learning Colors – Colorful Eggs on a Farm"[32]',
 '"Uptown Funk"[33]',
 '"Gangnam Style"[34]',
 '"Phonics Song with Two Words"[36]',
 '"Sugar"[37]',
 '"Dame Tu Cosita"[38]',
 '"Sorry"[39]',
 '"Roar"[40]',
 '"Counting Stars"[41]',
 '"Thinking Out Loud"[42]',
 '"Wheels on the Bus"[43]',
 '"Dark Horse"[44]',
 '"Faded"[45]',
 '"Shake It Off"[46]',
 '"Girls Like You"[47]',
 '"Lean On"[48]',
 '"Bailando"[49]',
 '"Let Her Go"[50]',
 '"Mi Gente"[51]',
 '"Perfect"[52]',
 '"Waka Waka (This Time for Africa)"[53]',
 '"Axel F"[54]',
 '"Hello"[55]']

In [97]:
artist=[]
for i in range(1,31):        
    artist_tag=driver.find_element_by_xpath("/html/body/div[3]/div[3]/div[5]/div[1]/table[3]/tbody/tr[{}]/td[3]".format(i))
    artist.append(artist_tag.text)

In [98]:
artist

["Pinkfong Kids' Songs & Stories",
 'Luis Fonsi',
 'LooLoo Kids',
 'Ed Sheeran',
 'Wiz Khalifa',
 'Get Movies',
 'Cocomelon – Nursery Rhymes',
 'Miroshka TV',
 'Mark Ronson',
 'Psy',
 'ChuChu TV',
 'Maroon 5',
 'El Chombo',
 'Justin Bieber',
 'Katy Perry',
 'OneRepublic',
 'Ed Sheeran',
 'Cocomelon – Nursery Rhymes',
 'Katy Perry',
 'Alan Walker',
 'Taylor Swift',
 'Maroon 5',
 'Major Lazer',
 'Enrique Iglesias',
 'Passenger',
 'J Balvin',
 'Ed Sheeran',
 'Shakira',
 'Crazy Frog',
 'Adele']

In [99]:
views=[]
for i in range(1,31):        
    views_tag=driver.find_element_by_xpath("/html/body/div[3]/div[3]/div[5]/div[1]/table[3]/tbody/tr[{}]/td[4]".format(i))
    views.append(views_tag.text)

In [100]:
views

['8.95',
 '7.44',
 '5.54',
 '5.38',
 '5.17',
 '4.44',
 '4.29',
 '4.25',
 '4.22',
 '4.11',
 '3.98',
 '3.50',
 '3.45',
 '3.45',
 '3.38',
 '3.34',
 '3.29',
 '3.15',
 '3.10',
 '3.10',
 '3.07',
 '3.07',
 '3.06',
 '3.06',
 '3.02',
 '2.94',
 '2.89',
 '2.88',
 '2.87',
 '2.85']

In [101]:
date=[]
for i in range(1,31):        
    date_tag=driver.find_element_by_xpath("/html/body/div[3]/div[3]/div[5]/div[1]/table[3]/tbody/tr[{}]/td[5]".format(i))
    date.append(date_tag.text)

In [102]:
date

['June 17, 2016',
 'January 12, 2017',
 'October 8, 2016',
 'January 30, 2017',
 'April 6, 2015',
 'January 31, 2012',
 'May 2, 2018',
 'February 27, 2018',
 'November 19, 2014',
 'July 15, 2012',
 'March 6, 2014',
 'January 14, 2015',
 'April 5, 2018',
 'October 22, 2015',
 'September 5, 2013',
 'May 31, 2013',
 'October 7, 2014',
 'May 24, 2018',
 'February 20, 2014',
 'December 3, 2015',
 'August 18, 2014',
 'May 31, 2018',
 'March 22, 2015',
 'April 11, 2014',
 'July 25, 2012',
 'June 29, 2017',
 'November 9, 2017',
 'June 4, 2010',
 'June 16, 2009',
 'October 22, 2015']

In [105]:
Video=pd.DataFrame({})
Video["Rank"]=rank
Video["Video Name"]=video_name
Video["Artist"]=artist
Video["Date"]=date
Video["Views in Billions"]=views

In [106]:
Video

,Rank,Video Name,Artist,Date,Views in Billions
0,1,"""Baby Shark Dance""[22]",Pinkfong Kids' Songs & Stories,"June 17, 2016",8.95
1,2,"""Despacito""[24]",Luis Fonsi,"January 12, 2017",7.44
2,3,"""Johny Johny Yes Papa""[25]",LooLoo Kids,"October 8, 2016",5.54
3,4,"""Shape of You""[26]",Ed Sheeran,"January 30, 2017",5.38
4,5,"""See You Again""[27]",Wiz Khalifa,"April 6, 2015",5.17
5,6,"""Masha and the Bear – Recipe for Disaster""[30]",Get Movies,"January 31, 2012",4.44
6,7,"""Bath Song""[31]",Cocomelon – Nursery Rhymes,"May 2, 2018",4.29
7,8,"""Learning Colors – Colorful Eggs on a Farm""[32]",Miroshka TV,"February 27, 2018",4.25
8,9,"""Uptown Funk""[33]",Mark Ronson,"November 19, 2014",4.22
9,10,"""Gangnam Style""[34]",Psy,"July 15, 2012",4.11
10,11,"""Phonics Song with Two Words""[36]",ChuChu TV,"March 6, 2014",3.98
11,12,"""Sugar""[37]",Maroon 5,"January 14, 2015",3.50
12,13,"""Dame Tu Cosita""[38]",El Chombo,"April 5, 2018",3.45
13,14,"""Sorry""[39]",Justin Bieber,"October 22, 2015",3.45
14,15,"""Roar""[40]",Katy Perry,"September 5, 2013",3.38
15,16,"""Counting Stars""[41]",OneRepublic,"May 31, 2013",3.34
16,17,"""Thinking Out Loud""[42]",Ed Sheeran,"October 7, 2014",3.29
17,18,"""Wheels on the Bus""[43]",Cocomelon – Nursery Rhymes,"May 24, 2018",3.15
18,19,"""Dark Horse""[44]",Katy Perry,"February 20, 2014",3.10
19,20,"""Faded""[45]",Alan Walker,"December 3, 2015",3.10
20,21,"""Shake It Off""[46]",Taylor Swift,"August 18, 2014",3.07
21,22,"""Girls Like You""[47]",Maroon 5,"May 31, 2018",3.07
22,23,"""Lean On""[48]",Major Lazer,"March 22, 2015",3.06
23,24,"""Bailando""[49]",Enrique Iglesias,"April 11, 2014",3.06
24,25,"""Let Her Go""[50]",Passenger,"July 25, 2012",3.02
25,26,"""Mi Gente""[51]",J Balvin,"June 29, 2017",2.94
26,27,"""Perfect""[52]",Ed Sheeran,"November 9, 2017",2.89
27,28,"""Waka Waka (This Time for Africa)""[53]",Shakira,"June 4, 2010",2.88
28,29,"""Axel F""[54]",Crazy Frog,"June 16, 2009",2.87
29,30,"""Hello""[55]",Adele,"October 22, 2015",2.85

In [108]:
import re

In [111]:
def name(a):
    if re.search('\[.*', a):
        pos = re.search('\[.*', a).start()
  
        return a[1:pos-1]
  
    else:
        return a

In [113]:
Video["Video Name"]=Video["Video Name"].apply(name)

In [114]:
Video

,Rank,Video Name,Artist,Date,Views in Billions
0,1,Baby Shark Dance,Pinkfong Kids' Songs & Stories,"June 17, 2016",8.95
1,2,Despacito,Luis Fonsi,"January 12, 2017",7.44
2,3,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",5.54
3,4,Shape of You,Ed Sheeran,"January 30, 2017",5.38
4,5,See You Again,Wiz Khalifa,"April 6, 2015",5.17
5,6,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.44
6,7,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",4.29
7,8,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.25
8,9,Uptown Funk,Mark Ronson,"November 19, 2014",4.22
9,10,Gangnam Style,Psy,"July 15, 2012",4.11
10,11,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",3.98
11,12,Sugar,Maroon 5,"January 14, 2015",3.50
12,13,Dame Tu Cosita,El Chombo,"April 5, 2018",3.45
13,14,Sorry,Justin Bieber,"October 22, 2015",3.45
14,15,Roar,Katy Perry,"September 5, 2013",3.38
15,16,Counting Stars,OneRepublic,"May 31, 2013",3.34
16,17,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.29
17,18,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",3.15
18,19,Dark Horse,Katy Perry,"February 20, 2014",3.10
19,20,Faded,Alan Walker,"December 3, 2015",3.10
20,21,Shake It Off,Taylor Swift,"August 18, 2014",3.07
21,22,Girls Like You,Maroon 5,"May 31, 2018",3.07
22,23,Lean On,Major Lazer,"March 22, 2015",3.06
23,24,Bailando,Enrique Iglesias,"April 11, 2014",3.06
24,25,Let Her Go,Passenger,"July 25, 2012",3.02
25,26,Mi Gente,J Balvin,"June 29, 2017",2.94
26,27,Perfect,Ed Sheeran,"November 9, 2017",2.89
27,28,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",2.88
28,29,Axel F,Crazy Frog,"June 16, 2009",2.87
29,30,Hello,Adele,"October 22, 2015",2.85

# 2. Scrape the details team India’s international fixtures from bcci.tv.
# Url = https://www.bcci.tv/.
# You need to find following details:
# A) Match title (I.e. 1st ODI)
# B) Series
# C) Place
# D) Date
# E) Time
# Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [240]:
driver = webdriver.Chrome(r"C:\Data Science\Flip Robo\Selenium\chromedriver_win32\chromedriver.exe")

In [236]:
driver.maximize_window()

In [241]:
url = "https://www.bcci.tv/"
driver.get(url)

In [242]:
urls=[]

In [244]:
fixture_url = driver.find_element_by_xpath('/html/body/div[3]/div/div[2]/div[2]/nav/ul/li[1]/div[2]/div/ul/li[1]/a')
urls.append(fixture_url.get_attribute('href'))

In [245]:
urls

['https://www.bcci.tv/international/fixtures']

In [246]:
for b in urls:
    driver.get(b)

In [247]:
match_title_tags=driver.find_elements_by_xpath("//strong[@class='fixture__name fixture__name--with-margin']")
match_title_tags

[<selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="30c93406-4e83-41d5-8fc9-d5693bc3fc79")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="df07eafb-c6dc-4933-b17c-e8503a8635af")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="ce52a511-fd44-4bcc-90d8-ba26ebd54f37")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="aa9f4e8d-ffc1-4efb-8b2f-1c337b68bca2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="b9638904-2ad1-4f78-b39c-f8cad0ef1ee5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="59b54de4-fecd-4fd1-a725-f93f5d62e8e8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="31ef1570-abad-4b1c-ac8b-ee9ac84c4e3d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="ea1dfac9-4a79-4f84-9932-7cc7327c80c9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="ce7ee068-1a0a-4cb6-8f8c-857b5d74f617")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="9d5825c7-1a94-48a6-8171-ead030d6f506")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="c4b47d06-e681-4a08-b95e-e44465547c80")>]

In [248]:
match_title=[]
for i in match_title_tags:        
    match_title.append(i.text.replace("\n",' '))

In [249]:
match_title

['1st ODI',
 '2nd ODI',
 '3rd ODI',
 '1st T20I',
 '2nd T20I',
 '3rd T20I',
 '1st Test',
 '2nd Test',
 '3rd Test',
 '4th Test',
 '5th Test']

In [250]:
series=[]
for i in range(1,12):        
    series_tags=driver.find_element_by_xpath("/html/body/div[4]/div/div/div[2]/section/div/div/a[{}]/div[3]".format(i))
    series.append(series_tags.text.replace("\n",' '))

In [251]:
series

['SRI LANKA v INDIA',
 'SRI LANKA v INDIA',
 'SRI LANKA v INDIA',
 'SRI LANKA v INDIA',
 'SRI LANKA v INDIA',
 'SRI LANKA v INDIA',
 'ENGLAND v INDIA',
 'ENGLAND v INDIA',
 'ENGLAND v INDIA',
 'ENGLAND v INDIA',
 'ENGLAND v INDIA']

In [252]:
place_tags=driver.find_elements_by_xpath("//p[@class='fixture__additional-info']//span")
place_tags

[<selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="d3975f8f-ef3c-4734-92d1-ecb1e0fc7f06")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="0e8f1365-358e-40bc-88e0-3dd9017e5ceb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="5736d650-e78e-4ac6-b3fa-f1a25b05967a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="3435750e-dc31-4bae-8a26-2bcc4d21a307")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="2e429554-e380-4c58-a183-d246d4c88a0f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="0d47d4d9-fcfd-4652-b34d-c60a7302a6f0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="5116615f-1f84-49e6-9a31-2b02c06f1f89")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="98e9f19a-6be2-4f8d-b472-cbe1111c68ed")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="1353dd84-107b-448e-992c-f53375863db5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="6d512686-57b6-4b8c-bc64-dc9483d6ecc1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="6af05c53-f2db-4505-a800-7830b7bfbf2a")>]

In [254]:
place=[]
for i in place_tags:        
    place.append(i.text.replace("\n",' '))

In [255]:
place

['R Premadasa Stadium, Colombo',
 'R Premadasa Stadium, Colombo',
 'R Premadasa Stadium, Colombo',
 'R Premadasa Stadium, Colombo',
 'R Premadasa Stadium, Colombo',
 'R Premadasa Stadium, Colombo',
 'Trent Bridge, Nottingham',
 "Lord's, London",
 'Headingley, Leeds',
 'The Oval, London',
 'Old Trafford, Manchester']

In [256]:
day_tags=driver.find_elements_by_xpath("//span[@class='fixture__date']")
day_tags

[<selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="5f9f64d9-5753-4bf6-aa5c-3776bc3d2f6a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="a5cc846c-3447-4161-b960-237d4c327871")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="3a1b8102-6636-4af0-ba2f-b12f21108337")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="02787259-a6a9-49f0-8388-6e2e4a0e4315")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="5ec0d75d-9c38-478a-9d1e-c72ae4b9cd2f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="ce8b4046-35eb-47ee-a0eb-8d4177d40d13")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="c31fed12-fa8e-4f44-8a38-11774b2a9b20")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="7c7bc18e-85ce-44dd-8014-250c9c968c95")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="52255225-32c2-473c-9dfb-345597f3666e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="3db18022-fc1d-4492-a7ff-14da43013193")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="437d33d9-aaeb-481f-ab58-aa87403f0f20")>]

In [257]:
day=[]
for i in day_tags:        
    day.append(i.text.replace("\n",' '))

In [258]:
day

['18', '20', '23', '25', '27', '29', '04', '12', '25', '02', '10']

In [259]:
month_tags=driver.find_elements_by_xpath("//span[@class='fixture__month']")
month_tags

[<selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="7559e277-9580-46c0-9153-9139c222dd4e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="acd6a099-de90-4f56-9ca4-97613c643aea")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="18fa533b-6ff7-4a67-aef3-bc37a19d3147")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="bd8efa91-a3a4-4c03-98d0-b6a801388be1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="cb32e072-c139-4c4e-b0ab-b132c3b64a51")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="8959e86b-16c6-4290-9f37-d99b4a27f2bd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="42749b83-10c6-4ce9-9f6c-ed637e483597")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="2ef42cc1-a6ae-4bc8-b835-b3bec8296299")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="a610f0d9-b6bb-4723-8015-e572b33fc6f7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="b20e2118-85d0-465a-bf07-ff9c07b0e99e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="80312d5a-00eb-4726-95c0-678b8f608d38")>]

In [260]:
month=[]
for i in month_tags:        
    month.append(i.text.replace("\n",' '))

In [261]:
month

['JULY',
 'JULY',
 'JULY',
 'JULY',
 'JULY',
 'JULY',
 'AUGUST',
 'AUGUST',
 'AUGUST',
 'SEPTEMBER',
 'SEPTEMBER']

In [262]:
time_tags=driver.find_elements_by_xpath("//span[@class='fixture__time']")
time_tags

[<selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="9809effe-f452-4a91-9d89-8fcbcc6adfdc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="18f1ed6e-69cf-4131-bcc4-c8311fc0e7ba")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="83c53550-e40c-46bf-9be8-a3b3110c650b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="c78b3f8c-18b4-48e3-b4aa-7c60c2207557")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="41bd3d23-d243-4172-8cf1-adc0abb66b6b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="02c123b7-be71-4295-8201-3042c1979024")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="64f18474-37d1-4e6c-8ab6-f44db9b09d77")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="94d9f28d-d592-41fc-8222-5b12f61b1558")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="b2d66579-6b12-4182-8631-841a44e74b4d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="5f5b4a35-26da-44f0-850e-8b6b457f5b6d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="d9a0022b03f0c578de755f92dac254f6", element="6aa2d50a-34e9-4355-ade6-0443acb37a42")>]

In [263]:
time=[]
for i in time_tags:        
    time.append(i.text.replace("\n",' '))

In [264]:
time

['15:00 IST',
 '15:00 IST',
 '15:00 IST',
 '20:00 IST',
 '20:00 IST',
 '20:00 IST',
 '15:30 IST',
 '15:30 IST',
 '15:30 IST',
 '15:30 IST',
 '15:30 IST']

In [265]:
Match=pd.DataFrame({})
Match["Match Title"]=match_title
Match["Series"]=series
Match["Place"]=place
Match["Day"]=day
Match["Month"]=month

In [266]:
Match

   Match Title             Series                         Place Day      Month
0      1st ODI  SRI LANKA v INDIA  R Premadasa Stadium, Colombo  18       JULY
1      2nd ODI  SRI LANKA v INDIA  R Premadasa Stadium, Colombo  20       JULY
2      3rd ODI  SRI LANKA v INDIA  R Premadasa Stadium, Colombo  23       JULY
3     1st T20I  SRI LANKA v INDIA  R Premadasa Stadium, Colombo  25       JULY
4     2nd T20I  SRI LANKA v INDIA  R Premadasa Stadium, Colombo  27       JULY
5     3rd T20I  SRI LANKA v INDIA  R Premadasa Stadium, Colombo  29       JULY
6     1st Test    ENGLAND v INDIA      Trent Bridge, Nottingham  04     AUGUST
7     2nd Test    ENGLAND v INDIA                Lord's, London  12     AUGUST
8     3rd Test    ENGLAND v INDIA             Headingley, Leeds  25     AUGUST
9     4th Test    ENGLAND v INDIA              The Oval, London  02  SEPTEMBER
10    5th Test    ENGLAND v INDIA      Old Trafford, Manchester  10  SEPTEMBER

In [267]:
Match["Date"]=Match["Day"]+" "+Match["Month"]
Match=Match.drop("Day",axis=1)
Match=Match.drop("Month",axis=1)
Match["time"]=time

In [268]:
Match

,Match Title,Series,Place,Date,time
0,1st ODI,SRI LANKA v INDIA,"R Premadasa Stadium, Colombo",18 JULY,15:00 IST
1,2nd ODI,SRI LANKA v INDIA,"R Premadasa Stadium, Colombo",20 JULY,15:00 IST
2,3rd ODI,SRI LANKA v INDIA,"R Premadasa Stadium, Colombo",23 JULY,15:00 IST
3,1st T20I,SRI LANKA v INDIA,"R Premadasa Stadium, Colombo",25 JULY,20:00 IST
4,2nd T20I,SRI LANKA v INDIA,"R Premadasa Stadium, Colombo",27 JULY,20:00 IST
5,3rd T20I,SRI LANKA v INDIA,"R Premadasa Stadium, Colombo",29 JULY,20:00 IST
6,1st Test,ENGLAND v INDIA,"Trent Bridge, Nottingham",04 AUGUST,15:30 IST
7,2nd Test,ENGLAND v INDIA,"Lord's, London",12 AUGUST,15:30 IST
8,3rd Test,ENGLAND v INDIA,"Headingley, Leeds",25 AUGUST,15:30 IST
9,4th Test,ENGLAND v INDIA,"The Oval, London",02 SEPTEMBER,15:30 IST
10,5th Test,ENGLAND v INDIA,"Old Trafford, Manchester",10 SEPTEMBER,15:30 IST

# 3. Scrape the details of selenium exception from guru99.com.
# Url = https://www.guru99.com/
# You need to find following details:
# A) Name
# B) Description
# Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [269]:
driver = webdriver.Chrome(r"C:\Data Science\Flip Robo\Selenium\chromedriver_win32\chromedriver.exe")

In [270]:
url = "https://www.guru99.com/"
driver.get(url)

In [273]:
urls=[]

In [274]:
selenium_url = driver.find_element_by_xpath('//a[@title="Selenium"]')
urls.append(selenium_url.get_attribute('href'))

In [275]:
urls

['https://www.guru99.com/selenium-tutorial.html']

In [277]:
for b in urls:
    driver.get(b)

In [280]:
urls=[]

In [281]:
selenium_url = driver.find_element_by_xpath('//a[@title="Selenium Exception Handling (Common Exceptions List)"]')
urls.append(selenium_url.get_attribute('href'))

In [282]:
urls

['https://www.guru99.com/exception-handling-selenium.html']

In [283]:
for b in urls:
    driver.get(b)

In [291]:
name=[]
for i in range(2,43):        
    name_tags=driver.find_element_by_xpath("/html/body/div[2]/section[3]/div/div[1]/main/div/div/div/div/div/div/div[2]/table/tbody/tr[{}]/td[1]".format(i))
    name.append(name_tags.text.replace("\n",' '))

In [287]:
name

['ElementNotVisibleException',
 'ElementNotSelectableException',
 'NoSuchElementException',
 'NoSuchFrameException',
 'NoAlertPresentException',
 'NoSuchWindowException',
 'StaleElementReferenceException',
 'SessionNotFoundException',
 'TimeoutException',
 'WebDriverException',
 'ConnectionClosedException',
 'ElementClickInterceptedException',
 'ElementNotInteractableException',
 'ErrorInResponseException',
 'ErrorHandler.UnknownServerException',
 'ImeActivationFailedException',
 'ImeNotAvailableException',
 'InsecureCertificateException',
 'InvalidArgumentException',
 'InvalidCookieDomainException',
 'InvalidCoordinatesException',
 'InvalidElementStateExceptio',
 'InvalidSessionIdException',
 'InvalidSwitchToTargetException',
 'JavascriptException',
 'JsonException',
 'NoSuchAttributeException',
 'MoveTargetOutOfBoundsException',
 'NoSuchContextException',
 'NoSuchCookieException',
 'NotFoundException',
 'RemoteDriverServerException',
 'ScreenshotException',
 'SessionNotCreatedException',
 'UnableToSetCookieException',
 'UnexpectedTagNameException',
 'UnhandledAlertException',
 'UnexpectedAlertPresentException',
 'UnknownMethodException',
 'UnreachableBrowserException',
 'UnsupportedCommandException']

In [292]:
desc=[]
for i in range(2,43):        
    desc_tags=driver.find_element_by_xpath("/html/body/div[2]/section[3]/div/div[1]/main/div/div/div/div/div/div/div[2]/table/tbody/tr[{}]/td[2]".format(i))
    desc.append(desc_tags.text.replace("\n",' '))

In [293]:
desc

['This type of Selenium exception occurs when an existing element in DOM has a feature set as hidden.',
 'This Selenium exception occurs when an element is presented in the DOM, but you can be able to select. Therefore, it is not possible to interact.',
 'This Exception occurs if an element could not be found.',
 'This Exception occurs if the frame target to be switched to does not exist.',
 'This Exception occurs when you switch to no presented alert.',
 'This Exception occurs if the window target to be switch does not exist.',
 'This Selenium exception occurs happens when the web element is detached from the current DOM.',
 'The WebDriver is acting after you quit the browser.',
 "Thrown when there is not enough time for a command to be completed. For Example, the element searched wasn't found in the specified time.",
 'This Exception takes place when the WebDriver is acting right after you close the browser.',
 'This type of Exception takes place when there is a disconnection in the driver.',
 'The command may not be completed as the element receiving the events is concealing the element which was requested clicked.',
 'This Selenium exception is thrown when any element is presented in the DOM. However, it is impossible to interact with such an element.',
 'This happens while interacting with the Firefox extension or the remote driver server.',
 'Exception is used as a placeholder in case if the server returns an error without a stack trace.',
 'This expectation will occur when IME engine activation has failed.',
 'It takes place when IME support is unavailable.',
 'Navigation made the user agent to hit a certificate warning. This can cause by an invalid or expired TLS certificate.',
 'It occurs when an argument does not belong to the expected type.',
 'This happens when you try to add a cookie under a different domain instead of current URL.',
 'This type of Exception matches an interacting operation that is not valid.',
 "It occurs when command can't be finished when the element is invalid.",
 'This Exception took place when the given session ID is not included in the list of active sessions. It means the session does not exist or is inactive either.',
 'This occurs when the frame or window target to be switched does not exist.',
 'This issue occurs while executing JavaScript given by the user.',
 'It occurs when you afford to get the session when the session is not created.',
 'This kind of Exception occurs when the attribute of an element could not be found.',
 'It takes place if the target provided to the ActionChains move() methodology is not valid. For Example, out of the document.',
 'ContextAware does mobile device testing.',
 'This Exception occurs when no cookie matching with the given pathname found for all the associated cookies of the currently browsing document.',
 'This Exception is a subclass of WebDriverException. This will occur when an element on the DOM does not exist.',
 'This Selenium exception is thrown when the server is not responding because of the problem that the capabilities described are not proper.',
 'It is not possible to capture a screen.',
 'It happens when a new session could not be successfully created.',
 'This occurs if a driver is unable to set a cookie.',
 'Happens if a support class did not get a web element as expected.',
 'This expectation occurs when there is an alert, but WebDriver is not able to perform Alert operation.',
 'It occurs when there is the appearance of an unexpected alert.',
 'This Exception happens when the requested command matches with a known URL but and not matching with a methodology for a specific URL.',
 'This Exception occurs only when the browser is not able to be opened or crashed because of some reason.',
 "This occurs when remote WebDriver does n't send valid commands as expected."]

In [296]:
Exceptions=pd.DataFrame({})
Exceptions["Name"]=name
Exceptions["Descriptiion"]=desc

In [297]:
Exceptions

,Name,Descriptiion
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can't be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

# 4. Scrape the details of State-wise GDP of India from statisticstime.com.
# Url = http://statisticstimes.com/
# You have to find following details:
# A) Rank
# B) State
# C) GSDP at current price (19-20)
# D) GSDP at current price (18-19)
# E) Share(18-19)
# F) GDP( billion)
# Note: - From statisticstimes home page you have to reach to economy page through code

In [423]:
driver = webdriver.Chrome(r"C:\Data Science\Flip Robo\Selenium\chromedriver_win32\chromedriver.exe")

In [424]:
import time

In [425]:
url = "http://statisticstimes.com/"
driver.get(url)
time.sleep(5)

In [426]:
urls=[]

In [427]:
gdp_url = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
urls.append(gdp_url.get_attribute('href'))

In [428]:
urls

['http://statisticstimes.com/economy/india-statistics.php']

In [429]:
for b in urls:
    driver.get(b)

In [430]:
urls=[]

In [431]:
gdp_url = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
urls.append(gdp_url.get_attribute('href'))

In [432]:
urls

['http://statisticstimes.com/economy/india/indian-states-gdp.php']

In [433]:
for b in urls:
    driver.get(b)

In [434]:
rank=[]
for i in range(1,34):        
    rank_tags=driver.find_element_by_xpath("/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr[{}]/td[1]".format(i))
    rank.append(rank_tags.text.replace("\n",' '))

In [435]:
rank

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33']

In [436]:
state=[]
for i in range(1,34):        
    state_tags=driver.find_element_by_xpath("/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr[{}]/td[2]".format(i))
    state.append(state_tags.text.replace("\n",' '))

In [437]:
state

['Maharashtra',
 'Tamil Nadu',
 'Uttar Pradesh',
 'Gujarat',
 'Karnataka',
 'West Bengal',
 'Rajasthan',
 'Andhra Pradesh',
 'Telangana',
 'Madhya Pradesh',
 'Kerala',
 'Delhi',
 'Haryana',
 'Bihar',
 'Punjab',
 'Odisha',
 'Assam',
 'Chhattisgarh',
 'Jharkhand',
 'Uttarakhand',
 'Jammu & Kashmir',
 'Himachal Pradesh',
 'Goa',
 'Tripura',
 'Chandigarh',
 'Puducherry',
 'Meghalaya',
 'Sikkim',
 'Manipur',
 'Nagaland',
 'Arunachal Pradesh',
 'Mizoram',
 'Andaman & Nicobar Islands']

In [316]:
GSDP_19_20=[]
for i in range(1,34):        
    GSDP_19_20_tags=driver.find_element_by_xpath("/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr[{}]/td[3]".format(i))
    GSDP_19_20.append(GSDP_19_20_tags.text.replace("\n",' '))

In [317]:
GSDP_19_20

['-',
 '1,845,853',
 '1,687,818',
 '-',
 '1,631,977',
 '1,253,832',
 '1,020,989',
 '972,782',
 '969,604',
 '906,672',
 '-',
 '856,112',
 '831,610',
 '611,804',
 '574,760',
 '521,275',
 '-',
 '329,180',
 '328,598',
 '-',
 '-',
 '165,472',
 '80,449',
 '55,984',
 '-',
 '38,253',
 '36,572',
 '32,496',
 '31,790',
 '-',
 '-',
 '26,503',
 '-']

In [438]:
GSDP_18_19=[]
for i in range(1,34):        
    GSDP_18_19_tags=driver.find_element_by_xpath("/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr[{}]/td[4]".format(i))
    GSDP_18_19.append(GSDP_18_19_tags.text.replace("\n",' '))

In [439]:
GSDP_18_19

['2,632,792',
 '1,630,208',
 '1,584,764',
 '1,502,899',
 '1,493,127',
 '1,089,898',
 '942,586',
 '862,957',
 '861,031',
 '809,592',
 '781,653',
 '774,870',
 '734,163',
 '530,363',
 '526,376',
 '487,805',
 '315,881',
 '304,063',
 '297,204',
 '245,895',
 '155,956',
 '153,845',
 '73,170',
 '49,845',
 '42,114',
 '34,433',
 '33,481',
 '28,723',
 '27,870',
 '27,283',
 '24,603',
 '22,287',
 '-']

In [440]:
share=[]
for i in range(1,34):        
    share_tags=driver.find_element_by_xpath("/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr[{}]/td[5]".format(i))
    share.append(share_tags.text.replace("\n",' '))

In [441]:
share

['13.94%',
 '8.63%',
 '8.39%',
 '7.96%',
 '7.91%',
 '5.77%',
 '4.99%',
 '4.57%',
 '4.56%',
 '4.29%',
 '4.14%',
 '4.10%',
 '3.89%',
 '2.81%',
 '2.79%',
 '2.58%',
 '1.67%',
 '1.61%',
 '1.57%',
 '1.30%',
 '0.83%',
 '0.81%',
 '0.39%',
 '0.26%',
 '0.22%',
 '0.18%',
 '0.18%',
 '0.15%',
 '0.15%',
 '0.14%',
 '0.13%',
 '0.12%',
 '-']

In [442]:
GSDP_billion=[]
for i in range(1,34):        
    GSDP_billion_tags=driver.find_element_by_xpath("/html/body/div[3]/div[2]/div[5]/div[1]/div/table/tbody/tr[{}]/td[6]".format(i))
    GSDP_billion.append(GSDP_billion_tags.text.replace("\n",' '))

In [443]:
GSDP_billion

['399.921',
 '247.629',
 '240.726',
 '228.290',
 '226.806',
 '165.556',
 '143.179',
 '131.083',
 '130.791',
 '122.977',
 '118.733',
 '117.703',
 '111.519',
 '80.562',
 '79.957',
 '74.098',
 '47.982',
 '46.187',
 '45.145',
 '37.351',
 '23.690',
 '23.369',
 '11.115',
 '7.571',
 '6.397',
 '5.230',
 '5.086',
 '4.363',
 '4.233',
 '4.144',
 '3.737',
 '3.385',
 '-']

In [444]:
GDP=pd.DataFrame({})
GDP["Rank"]=rank
GDP["State"]=state
GDP["GSDP at current price (19-20)"]=GSDP_19_20
GDP[" GSDP at current price (18-19)"]=GSDP_18_19
GDP["Share(18-19)"]=share
GDP["GDP($ billion)"]=GSDP_billion

In [445]:
GDP

,Rank,State,GSDP at current price (19-20),GSDP at current price (18-19),Share(18-19),GDP($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# 5. Scrape the details of trending repositories on Github.com.
# Url = https://github.com/
# You have to find the following details:
# A) Repository title
# B) Repository description
# C) Contributors count
# D) Language used
# Note: - From the home page you have to click on the trending option from Explore menu through code

In [379]:
driver = webdriver.Chrome(r"C:\Data Science\Flip Robo\Selenium\chromedriver_win32\chromedriver.exe")

In [380]:
url = "https://github.com/"
driver.get(url)

In [381]:
urls=[]

In [383]:
trending_url = driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[2]/li[3]/a')
urls.append(trending_url.get_attribute('href'))

In [384]:
urls

['https://github.com/trending']

In [385]:
for b in urls:
    driver.get(b)

In [386]:
title=[]
for i in range(1,26):        
    title_tags=driver.find_element_by_xpath("/html/body/div[4]/main/div[3]/div/div[2]/article[{}]/h1".format(i))
    title.append(title_tags.text.replace("\n",' '))

In [389]:
title

['chefyuan / algorithm-base',
 'trekhleb / javascript-algorithms',
 'airbnb / javascript',
 '30-seconds / 30-seconds-of-code',
 'earthly / earthly',
 'nvm-sh / nvm',
 'microsoft / IoT-For-Beginners',
 'bndw / wifi-card',
 'austinsonger / Incident-Playbook',
 'ryanmcdermott / clean-code-javascript',
 'lydiahallie / javascript-questions',
 'sorrycc / awesome-javascript',
 'jaywcjlove / awesome-mac',
 'go-kratos / kratos',
 'laynH / Anime-Girls-Holding-Programming-Books',
 'swisskyrepo / PayloadsAllTheThings',
 'goldbergyoni / nodebestpractices',
 'shufflewzc / faker2',
 'rosinality / alias-free-gan-pytorch',
 'fenixsoft / awesome-fenix',
 'mikel-brostrom / Yolov5_DeepSort_Pytorch',
 'TheAlphamerc / flutter_ecommerce_app',
 'facebook / folly',
 'ailabstw / social-distancing-ios',
 'Vishal-raj-1 / Awesome-JavaScript-Projects']

In [390]:
desc=[]
for i in range(1,26):        
    desc_tags=driver.find_element_by_xpath("/html/body/div[4]/main/div[3]/div/div[2]/article[{}]/p".format(i))
    desc.append(desc_tags.text)

In [391]:
desc

['专门为刚开始刷题的同学准备的算法基地，没有最细只有更细，立志用动画将晦涩难懂的算法说的通俗易懂！',
 '📝 Algorithms and data structures implemented in JavaScript with explanations and links to further readings',
 'JavaScript Style Guide',
 'Short JavaScript code snippets for all your development needs',
 'Build automation for the container era',
 'Node Version Manager - POSIX-compliant bash script to manage multiple active node.js versions',
 '12 Weeks, 24 Lessons, IoT for All!',
 '📶 Print a QR code for connecting to your WiFi',
 'GOAL: Incident Response Playbooks Mapped to MITRE Attack Tactics and Techniques. [Contributors Friendly]',
 '🛁 Clean Code concepts adapted for JavaScript',
 'A long list of (advanced) JavaScript questions, and their explanations ✨',
 '🐢 A collection of awesome browser-side JavaScript libraries, resources and shiny things.',
 '\uf8ff Now we have become very big, Different from the original idea. Collect premium software in various categories.',
 'A Go framework for microservices.',
 'Anime Girls Holding Programming Books',
 'A list of useful payloads and bypass for Web Application Security and Pentest/CTF',
 '✅ The Node.js best practices list (June 2021)',
 '不知名大佬备份',
 'Unofficial implementation of Alias-Free Generative Adversarial Networks. (https://arxiv.org/abs/2106.12423) in PyTorch',
 '讨论如何构建一套可靠的大型分布式系统',
 'Real-time multi-object tracker using YOLO v5 and deep sort',
 'E-Commerce App built in flutter',
 'An open-source C++ library developed and used at Facebook.',
 'Taiwan Social Distancing App - iOS',
 'This Repository contain awesome vanilla JavaScript projects.']

In [393]:
count=[]
for i in range(1,26):        
    count_tags=driver.find_element_by_xpath("/html/body/div[4]/main/div[3]/div/div[2]/article[{}]/div[2]/a[2]".format(i))
    count.append(count_tags.text)

In [394]:
count

['1,043',
 '18,728',
 '21,423',
 '8,621',
 '105',
 '5,080',
 '172',
 '90',
 '48',
 '6,754',
 '4,722',
 '3,517',
 '4,802',
 '2,794',
 '329',
 '7,699',
 '6,844',
 '137',
 '9',
 '200',
 '325',
 '681',
 '4,131',
 '28',
 '416']

In [396]:
lang=[]
for i in range(1,26):
    
    try:
        lang_tags=driver.find_element_by_xpath("/html/body/div[4]/main/div[3]/div/div[2]/article[{}]/div[2]/span[1]/span[2]".format(i))
        lang.append(lang_tags.text.replace("\n",'')) 
            
    except NoSuchElementException:                                                            
        lang.append("No Language")

In [397]:
lang

['Java',
 'JavaScript',
 'JavaScript',
 'JavaScript',
 'Go',
 'Shell',
 'C++',
 'JavaScript',
 'Python',
 'JavaScript',
 'No Language',
 'No Language',
 'JavaScript',
 'Go',
 'No Language',
 'Python',
 'JavaScript',
 'JavaScript',
 'Python',
 'Vue',
 'Python',
 'Dart',
 'C++',
 'Swift',
 'JavaScript']

In [399]:
Github=pd.DataFrame({})
Github["Repository title"]=title
Github["Repository description"]=desc
Github["Contributors count"]=count
Github["Language used"]=lang

In [400]:
Github

,Repository title,Repository description,Contributors count,Language used
0,chefyuan / algorithm-base,专门为刚开始刷题的同学准备的算法基地，没有最细只有更细，立志用动画将晦涩难懂的算法说的通俗易懂！,"1,043",Java
1,trekhleb / javascript-algorithms,📝 Algorithms and data structures implemented i...,"18,728",JavaScript
2,airbnb / javascript,JavaScript Style Guide,"21,423",JavaScript
3,30-seconds / 30-seconds-of-code,Short JavaScript code snippets for all your de...,"8,621",JavaScript
4,earthly / earthly,Build automation for the container era,105,Go
5,nvm-sh / nvm,Node Version Manager - POSIX-compliant bash sc...,"5,080",Shell
6,microsoft / IoT-For-Beginners,"12 Weeks, 24 Lessons, IoT for All!",172,C++
7,bndw / wifi-card,📶 Print a QR code for connecting to your WiFi,90,JavaScript
8,austinsonger / Incident-Playbook,GOAL: Incident Response Playbooks Mapped to MI...,48,Python
9,ryanmcdermott / clean-code-javascript,🛁 Clean Code concepts adapted for JavaScript,"6,754",JavaScript
10,lydiahallie / javascript-questions,A long list of (advanced) JavaScript questions...,"4,722",No Language
11,sorrycc / awesome-javascript,🐢 A collection of awesome browser-side JavaScr...,"3,517",No Language
12,jaywcjlove / awesome-mac," Now we have become very big, Different from ...","4,802",JavaScript
13,go-kratos / kratos,A Go framework for microservices.,"2,794",Go
14,laynH / Anime-Girls-Holding-Programming-Books,Anime Girls Holding Programming Books,329,No Language
15,swisskyrepo / PayloadsAllTheThings,A list of useful payloads and bypass for Web A...,"7,699",Python
16,goldbergyoni / nodebestpractices,✅ The Node.js best practices list (June 2021),"6,844",JavaScript
17,shufflewzc / faker2,不知名大佬备份,137,JavaScript
18,rosinality / alias-free-gan-pytorch,Unofficial implementation of Alias-Free Genera...,9,Python
19,fenixsoft / awesome-fenix,讨论如何构建一套可靠的大型分布式系统,200,Vue
20,mikel-brostrom / Yolov5_DeepSort_Pytorch,Real-time multi-object tracker using YOLO v5 a...,325,Python
21,TheAlphamerc / flutter_ecommerce_app,E-Commerce App built in flutter,681,Dart
22,facebook / folly,An open-source C++ library developed and used ...,"4,131",C++
23,ailabstw / social-distancing-ios,Taiwan Social Distancing App - iOS,28,Swift
24,Vishal-raj-1 / Awesome-JavaScript-Projects,This Repository contain awesome vanilla JavaSc...,416,JavaScript

# 6. Scrape the details of top 100 songs on billboard.com.
# Url = https://www.billboard.com/
# You have to find the following details:
# A) Song name
# B) Artist name
# C) Last week rank
# D) Peak rank
# E) Weeks on board
# Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [453]:
driver = webdriver.Chrome(r"C:\Data Science\Flip Robo\Selenium\chromedriver_win32\chromedriver.exe")

In [454]:
url = "https://www.billboard.com/"
driver.get(url)

In [455]:
driver.maximize_window()

In [461]:
urls=[]

In [462]:
hot100_url = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/nav/ul/li[3]/a')
urls.append(hot100_url.get_attribute('href'))

In [463]:
urls

['https://www.billboard.com/charts/hot-100']

In [464]:
for b in urls:
    driver.get(b)

In [473]:
song_tags = driver.find_elements_by_xpath('//span[@class="chart-element__information__song text--truncate color--primary"]')

In [474]:
song=[]
for i in song_tags:        
    song.append(i.text.replace("\n",' '))

In [476]:
song

['Butter',
 'Good 4 U',
 'Levitating',
 'Kiss Me More',
 'Montero (Call Me By Your Name)',
 'Bad Habits',
 'Leave The Door Open',
 'Peaches',
 'Save Your Tears',
 'Deja Vu',
 'Astronaut In The Ocean',
 'Rapstar',
 'You Right',
 'Am I The Only One',
 'Blinding Lights',
 'Without You',
 'Thot Shit',
 'Forever After All',
 'Heartbreak Anniversary',
 'Fancy Like',
 'Every Chance I Get',
 'Famous Friends',
 'Beautiful Mistakes',
 'Best Friend',
 'Lil Bit',
 'Single Saturday Night',
 'Heat Waves',
 'Leave Before You Love Me',
 'Wants And Needs',
 'Yonaguni',
 'Blame It On You',
 'Late At Night',
 'Drivers License',
 'Telepatia',
 'Glad You Exist',
 'Mood',
 'Wockesha',
 'Traitor',
 'Todo de Ti',
 "Drinkin' Beer. Talkin' God. Amen.",
 "Ain't Shit",
 'pov',
 "My Ex's Best Friend",
 'WUSYANAME',
 'Calling My Phone',
 "Beggin'",
 'Ball If I Want To',
 'Gone',
 'Wasting Time',
 'Red Light Green Light',
 'Things A Man Oughta Know',
 'Favorite Crime',
 'Settling Down',
 'Way Less Sad',
 'Straightenin',
 'Ski',
 'AM',
 'Arcade',
 'Happier',
 'You',
 'my.life',
 'Chasing After You',
 "Drunk (And I Don't Wanna Go Home)",
 'Need To Know',
 'Track Star',
 'One Too Many',
 'Hats Off',
 'Brutal',
 'Build A Bitch',
 "Breaking Up Was Easy In The 90's",
 'Country Again',
 'Fiel',
 'Renegade',
 'Waves',
 "We Didn't Have Much",
 'Minimum Wage',
 'Follow You',
 'Jealousy, Jealousy',
 'Come Through',
 'Twerkulator',
 'Cry No More',
 'Essence',
 'A-O-K',
 '4 Da Gang',
 'Tombstone',
 'Made For You',
 'Having Our Way',
 'My Boy',
 'transparentsoul',
 'You Should Probably Leave',
 'I Was On A Boat That Day',
 'Outside',
 'Working',
 'Miss The Rage',
 'Cold Beer Calling My Name',
 'All I Know So Far',
 "What's Next",
 'Enough For You',
 'Juggernaut',
 'Tell Em']

In [477]:
artist_tags = driver.find_elements_by_xpath('//span[@class="chart-element__information__artist text--truncate color--secondary"]')

In [478]:
artist=[]
for i in artist_tags:        
    artist.append(i.text.replace("\n",' '))

In [481]:
artist

['BTS',
 'Olivia Rodrigo',
 'Dua Lipa Featuring DaBaby',
 'Doja Cat Featuring SZA',
 'Lil Nas X',
 'Ed Sheeran',
 'Silk Sonic (Bruno Mars & Anderson .Paak)',
 'Justin Bieber Featuring Daniel Caesar & Giveon',
 'The Weeknd & Ariana Grande',
 'Olivia Rodrigo',
 'Masked Wolf',
 'Polo G',
 'Doja Cat & The Weeknd',
 'Aaron Lewis',
 'The Weeknd',
 'The Kid LAROI',
 'Megan Thee Stallion',
 'Luke Combs',
 'Giveon',
 'Walker Hayes',
 'DJ Khaled Featuring Lil Baby & Lil Durk',
 'Chris Young + Kane Brown',
 'Maroon 5 Featuring Megan Thee Stallion',
 'Saweetie Featuring Doja Cat',
 'Nelly & Florida Georgia Line',
 'Cole Swindell',
 'Glass Animals',
 'Marshmello X Jonas Brothers',
 'Drake Featuring Lil Baby',
 'Bad Bunny',
 'Jason Aldean',
 'Roddy Ricch',
 'Olivia Rodrigo',
 'Kali Uchis',
 'Dan + Shay',
 '24kGoldn Featuring iann dior',
 'Moneybagg Yo',
 'Olivia Rodrigo',
 'Rauw Alejandro',
 'Chase Rice Featuring Florida Georgia Line',
 'Doja Cat',
 'Ariana Grande',
 'Machine Gun Kelly X blackbear',
 'Tyler, The Creator Featuring YoungBoy Never Broke Again & Ty Dolla $ign',
 'Lil Tjay Featuring 6LACK',
 'Maneskin',
 'DaBaby',
 'Dierks Bentley',
 'Brent Faiyaz Featuring Drake',
 'DaBaby',
 'Lainey Wilson',
 'Olivia Rodrigo',
 'Miranda Lambert',
 'AJR',
 'Migos',
 'Young Thug & Gunna',
 'Nio Garcia X J Balvin X Bad Bunny',
 'Duncan Laurence',
 'Olivia Rodrigo',
 'Regard x Troye Sivan x Tate McRae',
 'J. Cole, 21 Savage & Morray',
 'Ryan Hurd With Maren Morris',
 'Elle King & Miranda Lambert',
 'Doja Cat',
 'Mooski',
 'Keith Urban Duet With P!nk',
 'Lil Baby, Lil Durk & Travis Scott',
 'Olivia Rodrigo',
 'Bella Poarch',
 'Sam Hunt',
 'Thomas Rhett',
 'Los Legendarios, Wisin & Jhay Cortez',
 'Big Red Machine Featuring Taylor Swift',
 'Luke Bryan',
 'Justin Moore',
 'Blake Shelton',
 'Imagine Dragons',
 'Olivia Rodrigo',
 'H.E.R. Featuring Chris Brown',
 'City Girls',
 'G Herbo Featuring Polo G & Lil Tjay',
 'Wizkid Featuring Tems',
 'Tai Verdes',
 '42 Dugg & Roddy Ricch',
 'Rod Wave',
 'Jake Owen',
 'Migos Featuring Drake',
 'Elvie Shane',
 'Willow Featuring Travis Barker',
 'Chris Stapleton',
 'Old Dominion',
 'MO3 X OG Bobby Billions',
 'Tate McRae X Khalid',
 'Trippie Redd & Playboi Carti',
 'Jameson Rodgers Featuring Luke Combs',
 'P!nk',
 'Drake',
 'Olivia Rodrigo',
 'Tyler, The Creator Featuring Lil Uzi Vert & Pharrell Williams',
 'Cochise & $NOT']

In [487]:
last_week_tags = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--last"]')

In [488]:
last_week=[]
for i in last_week_tags:        
    last_week.append(i.text.replace("\n",' '))

In [492]:
last_week

['1',
 '2',
 '4',
 '3',
 '8',
 '5',
 '6',
 '7',
 '9',
 '10',
 '12',
 '13',
 '11',
 '-',
 '18',
 '15',
 '16',
 '19',
 '20',
 '34',
 '28',
 '21',
 '17',
 '22',
 '23',
 '53',
 '25',
 '31',
 '26',
 '27',
 '35',
 '33',
 '29',
 '30',
 '54',
 '37',
 '44',
 '39',
 '32',
 '50',
 '24',
 '36',
 '43',
 '14',
 '46',
 '78',
 '56',
 '38',
 '-',
 '51',
 '70',
 '62',
 '52',
 '64',
 '61',
 '63',
 '41',
 '69',
 '58',
 '75',
 '65',
 '77',
 '76',
 '49',
 '71',
 '74',
 '72',
 '73',
 '67',
 '79',
 '86',
 '81',
 '-',
 '94',
 '87',
 '80',
 '90',
 '89',
 '91',
 '96',
 '-',
 '-',
 '-',
 '92',
 '97',
 '83',
 '82',
 '-',
 '85',
 '-',
 '-',
 '-',
 '100',
 '98',
 '-',
 '-',
 '-',
 '-',
 '40',
 '-']

In [493]:
peak_tags = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--peak"]')

In [494]:
peak=[]
for i in peak_tags:        
    peak.append(i.text.replace("\n",' '))

In [496]:
peak

['1',
 '1',
 '2',
 '3',
 '1',
 '5',
 '1',
 '1',
 '1',
 '3',
 '6',
 '1',
 '11',
 '14',
 '1',
 '8',
 '16',
 '2',
 '16',
 '20',
 '20',
 '21',
 '13',
 '14',
 '23',
 '26',
 '19',
 '28',
 '2',
 '10',
 '31',
 '20',
 '1',
 '25',
 '35',
 '1',
 '33',
 '9',
 '32',
 '40',
 '24',
 '27',
 '20',
 '14',
 '3',
 '46',
 '39',
 '26',
 '49',
 '50',
 '51',
 '16',
 '41',
 '54',
 '23',
 '18',
 '41',
 '58',
 '15',
 '60',
 '2',
 '62',
 '63',
 '38',
 '31',
 '62',
 '16',
 '12',
 '56',
 '32',
 '71',
 '62',
 '73',
 '74',
 '75',
 '67',
 '68',
 '24',
 '64',
 '51',
 '81',
 '82',
 '83',
 '67',
 '11',
 '32',
 '15',
 '88',
 '76',
 '90',
 '91',
 '92',
 '93',
 '11',
 '95',
 '74',
 '1',
 '14',
 '40',
 '64']

In [497]:
weeks_on_boad_tags = driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--week"]')

In [498]:
weeks_on_boad=[]
for i in weeks_on_boad_tags:        
    weeks_on_boad.append(i.text.replace("\n",' '))

In [500]:
weeks_on_boad

['7',
 '8',
 '40',
 '13',
 '15',
 '2',
 '18',
 '16',
 '30',
 '14',
 '21',
 '13',
 '2',
 '1',
 '83',
 '31',
 '4',
 '37',
 '21',
 '3',
 '10',
 '15',
 '18',
 '26',
 '16',
 '10',
 '25',
 '7',
 '18',
 '5',
 '11',
 '5',
 '26',
 '20',
 '22',
 '48',
 '11',
 '7',
 '6',
 '6',
 '2',
 '18',
 '47',
 '2',
 '21',
 '2',
 '3',
 '17',
 '1',
 '2',
 '8',
 '7',
 '17',
 '11',
 '8',
 '12',
 '2',
 '13',
 '7',
 '4',
 '8',
 '10',
 '11',
 '4',
 '20',
 '30',
 '5',
 '7',
 '8',
 '19',
 '10',
 '4',
 '1',
 '3',
 '3',
 '9',
 '14',
 '7',
 '5',
 '5',
 '1',
 '1',
 '1',
 '13',
 '15',
 '20',
 '4',
 '2',
 '4',
 '1',
 '1',
 '3',
 '3',
 '9',
 '1',
 '4',
 '16',
 '6',
 '2',
 '4']

In [501]:
Billboard=pd.DataFrame({})
Billboard["Song name"]=song
Billboard["Artist name"]=artist
Billboard["Last week rank"]=last_week
Billboard["Peak rank"]=peak
Billboard["Weeks on board"]=weeks_on_boad

In [502]:
Billboard

,Song name,Artist name,Last week rank,Peak rank,Weeks on board
0,Butter,BTS,1,1,7
1,Good 4 U,Olivia Rodrigo,2,1,8
2,Levitating,Dua Lipa Featuring DaBaby,4,2,40
3,Kiss Me More,Doja Cat Featuring SZA,3,3,13
4,Montero (Call Me By Your Name),Lil Nas X,8,1,15
...,...,...,...,...,...
95,All I Know So Far,P!nk,-,74,4
96,What's Next,Drake,-,1,16
97,Enough For You,Olivia Rodrigo,-,14,6
98,Juggernaut,"Tyler, The Creator Featuring Lil Uzi Vert & Ph...",40,40,2
99,Tell Em,Cochise & $NOT,-,64,4

# 7. Scrape the details of Data science recruiters from naukri.com.
# Url = https://www.naukri.com/
# You have to find the following details:
# A) Name
# B) Designation
# C) Company
# D) Skills they hire for
# E) Location
# Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [2]:
driver = webdriver.Chrome(r"C:\Data Science\Flip Robo\Selenium\chromedriver_win32\chromedriver.exe")

In [3]:
url = "https://www.naukri.com/"
driver.get(url)

In [4]:
driver.maximize_window()

In [5]:
urls=[]

In [7]:
recruiter_url = driver.find_element_by_xpath('/html/body/div[1]/div[1]/div/ul[1]/li[2]/a')
urls.append(recruiter_url.get_attribute('href'))

In [8]:
urls

['https://www.naukri.com/recruiters']

In [9]:
for b in urls:
    driver.get(b)

In [10]:
search_keyword = driver.find_element_by_xpath('//input[@class="sugInp"]') 
search_keyword

In [11]:
search_keyword.send_keys("Data Science")

In [13]:
button = driver.find_element_by_xpath('//button[@class="fl qsbSrch blueBtn"]') 
button.click()

In [14]:
name_tags = driver.find_elements_by_xpath('//span[@class="fl ellipsis"]')

In [15]:
name=[]
for i in name_tags:        
    name.append(i.text.replace("\n",' '))

In [18]:
name

['Aakash Harit',
 'shravan Kumar Gaddam',
 'MARSIAN Technologies LLP',
 'Anik Agrawal',
 'subhas patel',
 'Abhishek - Only Analytics Hiring - India and',
 'Institute for Financial Management and Resear',
 'Balu Ramesh',
 'Asif Lucknowi',
 'InstaFinancials',
 'Kalpana Dumpala',
 'Mubarak',
 'Kushal Rastogi',
 'Ruchi Dhote',
 'Mahesh Babu Channa',
 'Kapil Devang',
 'Manisha Yadav',
 'Riya Rajesh',
 'Rashmi Bhattacharjee',
 'Faizan Kareem',
 'Rithika dadwal',
 'Azahar Shaikh',
 'Sandhya Khandagale',
 'Shaun Rao',
 'Manas',
 'kumar',
 'Sunil Vedula',
 'Rajat Kumar',
 'Priya Khare',
 'Dhruv Dev Dubey',
 'Jayanth N',
 'SREEDHAR',
 'Radha Manivasagam',
 'Ravi Dubey',
 'Prateek Kumar',
 'Amit Sharma',
 'Kanan',
 'Shashikant Chaudhary',
 'Brad',
 'Rutuja Pawar',
 'Madhusudhan Sridhar',
 'Ankit Sinha',
 'Gaurav Chouhan',
 'Rashi Kacker',
 'Ashwini',
 'Balaji Kolli',
 'Rajani Nagaraj',
 'ROHIT Kumar',
 'Amir Chowdhury',
 'Shailja Mishra']

In [19]:
designation_tags = driver.find_elements_by_xpath('//span[@class="ellipsis clr"]')

In [20]:
designation=[]
for i in designation_tags:        
    designation.append(i.text.replace("\n",' '))

In [23]:
designation

['HR Manager',
 'Company Recruiter',
 'Company HR',
 'Company Recruiter',
 'Founder CEO',
 'Recruitment Lead Consultant',
 'Programme Manager',
 'HR Administrator',
 'Director',
 'Human Resource',
 'Executive Hiring',
 'Company HR',
 'Company HR',
 'Senior Executive Talent Acquisition',
 'HR Team Lead',
 'HR Manager',
 'HR Executive',
 'Manager Talent Acquisition',
 'HR Head',
 'HR MANAGER',
 'HR Recruiter',
 'Company Recruiter',
 'HR Recruiter',
 'Manager Human Resources',
 'Lead Talent acquisition',
 'Proprietor',
 'CEO',
 'Founder CEO',
 'Senior Manager',
 'Company Recruitment Head',
 'Project Manager',
 'Recruitment Consultant',
 'HR Executive',
 'Recruitment Manager',
 'Head',
 'Consultant',
 'senior technology instructor',
 'HR Recruiter/HR Excutive',
 'Manager, Technical Recruiting',
 'Technical Recruiter',
 'Erp Implementer',
 'Head Analytics',
 'Chief Technical Officer',
 'Sr Product Manager',
 'Director Global Delivery',
 'Co Founder',
 'HR Manager',
 'Architect',
 'Managing Partner',
 'HR Manager']

In [36]:
company_tags = driver.find_elements_by_xpath('//p[@class="highlightable"]//a[2]')

In [37]:
company=[]
for i in company_tags:        
    company.append(i.text.replace("\n",' '))

In [40]:
company

['Data Science Network',
 'Shore Infotech India Pvt. Ltd',
 'MARSIAN Technologies LLP',
 'Enerlytics Software Solutions Pvt Ltd',
 'LibraryXProject',
 'Apidel Technologies Division of Transpower',
 'IFMR',
 'Techvantage Systems Pvt Ltd',
 'Weupskill- Live Wire India',
 'CBL Data Science Private Limited',
 'Innominds Software',
 'MoneyTap',
 'QuantMagnum Technologies Pvt. Ltd.',
 'Bristlecone India Ltd',
 'SocialPrachar.com',
 'BISP Solutions',
 'Easi Tax',
 'Novelworx Digital Solutions',
 'AXESTRACK SOFTWARE SOLUTIONS PRIVATE...',
 'FirstTech Consaltants Pvt.Ltd',
 'Affine Analytics',
 'NEAL ANALYTICS SERVICES PVT LTD',
 'Compumatrice Multimedia Pvt Ltd',
 'Exela Technologies',
 'Autumn Leaf Consulting Services Private...',
 'trainin',
 'Nanoprecise Sci Corp',
 'R.S Consultancy &amp; Services',
 'Independent Consultant',
 'Confidential',
 'Dollarbird Information Services Pvt, Ltd',
 'JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED',
 'Techcovery',
 'HyrEzy Talent Solutions LLP',
 'Trisect',
 'ASCO consulting',
 'NY INST',
 '3D India Staffing Research &amp; Consulting...',
 'O.C. Tanner',
 'Demand Matrix',
 'MADHUSUDHAN SRIDHAR',
 'Suntech Global',
 'Strategic Consulting Lab',
 'Impel Labs Pvt. Ltd.',
 'MRP Advisers',
 'Saras Solutions India Pvt Ltd',
 'WildJasmine',
 'LNT Private Limited',
 'Granular.ai',
 'Certybox Pvt.Ltd.']

In [24]:
skills_tags = driver.find_elements_by_xpath('//div[@class="hireSec highlightable"]')

In [25]:
skills=[]
for i in skills_tags:        
    skills.append(i.text.replace("\n",' '))

In [28]:
skills

['Classic ASP Developer, Internet Marketing Professional, Data Science SME, Content Writers, SEO Professional, Revenue Professional',
 '.Net, Java, Data Science, Linux Administration, Sql Server Development, Winforms, Wcf Services, Wpf, Telecom Engineering, Technical Management, Software',
 'Data Science, Artificial Intelligence, Machine Learning, Business Analytics',
 'Mean Stack, javascript, angularjs, mongodb, Web Services, rest, express, Node.js, Big Data, iot, Data Science, Cloud Computing, saas, Aws',
 'Hadoop, Spark, Digital Strategy, Data Architecture, Command Center, Cdp, Dmp, Kafka, Data Science, Data Analysis, Big Data Analytics, Real Time Analysis, SQL',
 'Analytics, Business Intelligence, Business Analytics, Predictive Modeling, Predictive Analytics, Data Science, Data Analysis, Data Analytics, Big Data, Big',
 'Data Science',
 'Machine Learning, algorithms, Go Getter, Computer Science, spark, Big Data, hdfs, sql, cassandra, hadoop, python, scala, java, Data Science, Front End',
 'Technical Training, Software Development, Presentation Skills, B.tech, M.tech, B.e., mca, msc, Computer Science, freshers, jobs in indore, Data Science, itil',
 'Software Development, It Sales, Account Management, Data Analysis, Customer Service, Sr, Software Engineering, Mvc, Ajax, Asp.net, Html, C#, Javascript',
 'Qa, Ui/ux, Java Developer, Java Architect, C++/qt, Php, Lamp, Api, J2ee, Java, Soa, Esb, Middleware, Bigdata Achitect, Hadoop Architect, Deep',
 'Business Intelligence, Data Warehousing, Data Science, Business Analytics, Customer Support, Business Reporting, Bi',
 'Office Administration, Hr Administration, telecalling, client relationship management, Client Acquisition, Sales, Reception, HR, Recruitment, Onboarding, Human',
 'Qlikview, Qlik Sense, Microsoft Azure, Power Bi, Data Science, Machine Learning',
 'Social Media, digital media maketing, seo, smm, smo, sem, Content Wirting, social media marketing, social media manager, digital media marketing manager',
 'Big Data, Hadoop, Data Analytics, Data Science',
 'Telecalling, Client Interaction, Marketing, Research, Web Development, Social Media Marketing, Data Entry Operation, Excel, Ms Office, Invoicing',
 'Data Science',
 'Corporate Sales, Software Development, Software Sales, Marketing, Creative Designing, Corporate Planning, Senior Management, Crm, Client Relationship',
 'Data Analytics, Data Science, Machine Learning, Deep Learning, Nlp, Data Mining, Python, R, Database Administration, Text Mining',
 'Data Science, Machine Learning, Python, R, Deep Learning, Big Data, Hadoop',
 'Data Science, Artificial Intelligence, Machine Learning, Data Analytics',
 'Big Data, Data Science, Artificial Intelligence, Hadoop, Ui Development, Php, Freelancing, .Net, Software Testing, Sap, Leadership Hiring',
 'Java, Net, Angularjs, Hr, Infrastructure, Management, Project Management, Business Analysis, Data Science, Information Technology, Technology',
 'Software Architecture, Vp Engineering, Product Management, analytics, Data Science, Node.js, Principal Engineer, Big Data, python, angularjs, React.js',
 'Data Science, Hadoop, Rpas, Devops, Python, Aws, Teaching, Big Data',
 'Signal Processing, Machine Learning, Neural Networks, Data Science, Predictive Analytics, Time Series Analysis, Data Visualization, Technical Leadership, Data',
 'Web Technologies, Project Management, Software Architecture, Data Science, Object Oriented Programming, Computer Science, Electrical Engineering, Architecture',
 'Data Science, Artificial Intelligence, analytics, Business Intelligence, python, tableau, Power Bi, qlikview, sql, Data Warehousing, Data Visualization',
 'Server Administartion, Verilog, Vhdl, Digital Marketing, Market Research, Property Research, Legal, It And Non It Recruitment, Logistics, Supply Chain, Bfsi',
 'Data Analytics, Managed Services, Team Leading, python, Machine Learning, Google Analytics, Dmp, Aws, Campaign Analytics, Digital Campaigns, Audience',
 'Data Science, Machine Learning, Big Data Analytics, Spark, Python, R, Networking, Network Engineering, Placement, Training, Sql, Marketing, Mainframes, All',
 'Python, Artificial Intelligence, Machine Learning, Data Science',
 'Walmart Interra Skeps Expressstores indifi whitehatJr Practo Zylo Doctalk Medtrail',
 'Java, Python, Angularjs, Software Testing, Machine Learning, Data Science, Javascript, Django, React.js, Node.js, Augmented Reality, Virtual Reality, Advanced',
 'Machine Learning, Artificial Intelligence, Data Science, Software Engineering, Software Development, Graduate Engineer Trainee, Fresher, Data Analytics, Java',
 'C, C++, Artificial Intelligence, Python, Php, Web Development, Matlab, Data Science, Augmented Reality, C C++',
 'Relationship Management, Retail Sales, Private Banking, Mutual Funds, NISM, Equity, Finance, Financial Products, Financial Services, Verbal, Written',
 'Data Science, Software Engineering',
 'Data Science, Big Data Analytics, Digital Marketing, Content Writing, Ui Development, Database Development, Qa Automation, Python, Project Management',
 'Data Science, Recruitment, Salary',
 'B.Tech, Tableau, Statistics, R, Analytics, Time Series, Data Science, Business Solutions, SQL, Technical Skills, SSAS, SQL Server, Analysis Services, Qlikview',
 'Software Development, Business Intelligence, Big Data Analytics, Database Administration, Data Science, Microsoft Azure, Spark, Cassandra, Object Oriented',
 'Data Science, Node.js, Angularjs',
 'Data Science, Media Marketing, Resource Planning, Managed Services, Display Advertising, Machine Learning, Python, Etl, Sql',
 'Data Analysis, Learning, Data Science, Computer Science, Communication Skills',
 'Java, Hadoop, R, Machine Learning, Spark, Flume, Hdfs, Data Mining, Sas, Big, Data Science, Cloudera, Impala, Bigdata',
 'Software Development, Core Java, Unit Testing, Customer Experience, Problem Solving, Communication Skills, Mysql, Data Science, Sales Management, Analytics',
 'Machine Learning, Data Science, Product Management, New Product, Data Analysis, Computer Vision, Deep Learning, Python, Remote Sensing',
 'consulting, Education Counseling, Educational Sales, Institutional Sales, pmp, Data Science, Business Development, Revenue Generation, Sales Achievement, new']

In [30]:
location=[]
for i in range(1,26):
    for j in range(1,3):
        
    
        try:
            location_tags=driver.find_element_by_xpath("/html/body/div[3]/div/div[2]/div/div[2]/div[{}]/div[{}]/div[1]/div[1]/p/span[2]".format(i,j))
            location.append(location_tags.text.replace("\n",'')) 
            
        except NoSuchElementException:                                                            
            location.append("No Location")

In [33]:
location

['Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Ahmedabad',
 'UK - (london)',
 'Vadodara / Baroda',
 'Chennai',
 'Trivandrum',
 'Indore',
 'Bengaluru / Bangalore',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Pune',
 'Hyderabad / Secunderabad',
 'Bhopal',
 'Navi Mumbai',
 'Cochin',
 'Delhi',
 'Hyderabad / Secunderabad',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'No Location',
 'Delhi',
 'Bengaluru / Bangalore',
 'Bengaluru / Bangalore',
 'Mysoru / Mysore',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Ghaziabad',
 'Noida',
 'New Delhi',
 'Chennai',
 'Aligarh',
 'Salt Lake City',
 'Pune',
 'Bengaluru / Bangalore',
 'Mumbai',
 'Indore',
 'Bengaluru / Bangalore',
 'MYSORE',
 'Hyderabad / Secunderabad',
 'Bengaluru / Bangalore',
 'Mumbai',
 'No Location',
 'Noida']

In [41]:
Naukri=pd.DataFrame({})
Naukri["Name of the recruiter"]=name
Naukri["Designation"]=designation
Naukri["Company"]=company
Naukri["Skills they hire for"]=skills
Naukri["Location"]=location

In [42]:
Naukri

,Name of the recruiter,Designation,Company,Skills they hire for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
11,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
13,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
15,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
16,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
17,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
18,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
19,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
20,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
21,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
22,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
23,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
24,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
25,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
26,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",No Location
27,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Delhi
28,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
29,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
30,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
31,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Hyderabad / Secunderabad
32,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",Bengaluru / Bangalore
33,Ravi Dubey,Recruitment Manager,HyrEzy Talent Solutions LLP,Walmart Interra Skeps Expressstores indifi whi...,Ghaziabad
34,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac...",Noida
35,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
36,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Aligarh
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Pune
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
41,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Indore
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
44,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
46,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
47,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai
48,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",No Location
49,Shailja Mishra,HR Manager,Certybox Pvt.Ltd.,"consulting, Education Counseling, Educational ...",Noida

# 8. Scrape the details of Highest selling novels.
# Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
# You have to find the following details:
# A) Book name
# B) Author name
# C) Volumes sold
# D) Publisher
# E) Genre

In [2]:
driver = webdriver.Chrome(r"C:\Data Science\Flip Robo\Selenium\chromedriver_win32\chromedriver.exe")

In [3]:
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(url)
driver.maximize_window()

In [4]:
title=[]
for i in range(1,101):        
    title_tags=driver.find_element_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{}]/td[2]".format(i))
    title.append(title_tags.text)

In [5]:
title

['Da Vinci Code,The',
 'Harry Potter and the Deathly Hallows',
 "Harry Potter and the Philosopher's Stone",
 'Harry Potter and the Order of the Phoenix',
 'Fifty Shades of Grey',
 'Harry Potter and the Goblet of Fire',
 'Harry Potter and the Chamber of Secrets',
 'Harry Potter and the Prisoner of Azkaban',
 'Angels and Demons',
 "Harry Potter and the Half-blood Prince:Children's Edition",
 'Fifty Shades Darker',
 'Twilight',
 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
 'Fifty Shades Freed',
 'Lost Symbol,The',
 'New Moon',
 'Deception Point',
 'Eclipse',
 'Lovely Bones,The',
 'Curious Incident of the Dog in the Night-time,The',
 'Digital Fortress',
 'Short History of Nearly Everything,A',
 'Girl Who Played with Fire,The:Millennium Trilogy',
 'Breaking Dawn',
 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar',
 'Gruffalo,The',
 "Jamie's 30-Minute Meals",
 'Kite Runner,The',
 'One Day',
 'Thousand Splendid Suns,A',
 "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy",
 "Time Traveler's Wife,The",
 'Atonement',
 "Bridget Jones's Diary:A Novel",
 'World According to Clarkson,The',
 "Captain Corelli's Mandolin",
 'Sound of Laughter,The',
 'Life of Pi',
 'Billy Connolly',
 'Child Called It,A',
 "Gruffalo's Child,The",
 "Angela's Ashes:A Memoir of a Childhood",
 'Birdsong',
 'Northern Lights:His Dark Materials S.',
 'Labyrinth',
 'Harry Potter and the Half-blood Prince',
 'Help,The',
 'Man and Boy',
 'Memoirs of a Geisha',
 "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.",
 'Island,The',
 'PS, I Love You',
 'You are What You Eat:The Plan That Will Change Your Life',
 'Shadow of the Wind,The',
 'Tales of Beedle the Bard,The',
 'Broker,The',
 "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P",
 'Subtle Knife,The:His Dark Materials S.',
 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation',
 "Delia's How to Cook:(Bk.1)",
 'Chocolat',
 'Boy in the Striped Pyjamas,The',
 "My Sister's Keeper",
 'Amber Spyglass,The:His Dark Materials S.',
 'To Kill a Mockingbird',
 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin',
 'Dear Fatty',
 'Short History of Tractors in Ukrainian,A',
 'Hannibal',
 'Lord of the Rings,The',
 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio',
 'Interpretation of Murder,The',
 'Sharon Osbourne Extreme:My Autobiography',
 'Alchemist,The:A Fable About Following Your Dream',
 "At My Mother's Knee ...:and Other Low Joints",
 'Notes from a Small Island',
 'Return of the Naked Chef,The',
 'Bridget Jones: The Edge of Reason',
 "Jamie's Italy",
 'I Can Make You Thin',
 'Down Under',
 'Summons,The',
 'Small Island',
 'Nigella Express',
 'Brick Lane',
 "Memory Keeper's Daughter,The",
 'Room on the Broom',
 'About a Boy',
 'My Booky Wook',
 'God Delusion,The',
 '"Beano" Annual,The',
 'White Teeth',
 'House at Riverton,The',
 'Book Thief,The',
 'Nights of Rain and Stars',
 'Ghost,The',
 'Happy Days with the Naked Chef',
 'Hunger Games,The:Hunger Games Trilogy',
 "Lost Boy,The:A Foster Child's Search for the Love of a Family",
 "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [6]:
author=[]
for i in range(1,101):        
    author_tags=driver.find_element_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{}]/td[3]".format(i))
    author.append(author_tags.text)

In [7]:
author

['Brown, Dan',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'James, E. L.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Rowling, J.K.',
 'Brown, Dan',
 'Rowling, J.K.',
 'James, E. L.',
 'Meyer, Stephenie',
 'Larsson, Stieg',
 'James, E. L.',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Brown, Dan',
 'Meyer, Stephenie',
 'Sebold, Alice',
 'Haddon, Mark',
 'Brown, Dan',
 'Bryson, Bill',
 'Larsson, Stieg',
 'Meyer, Stephenie',
 'Carle, Eric',
 'Donaldson, Julia',
 'Oliver, Jamie',
 'Hosseini, Khaled',
 'Nicholls, David',
 'Hosseini, Khaled',
 'Larsson, Stieg',
 'Niffenegger, Audrey',
 'McEwan, Ian',
 'Fielding, Helen',
 'Clarkson, Jeremy',
 'Bernieres, Louis de',
 'Kay, Peter',
 'Martel, Yann',
 'Stephenson, Pamela',
 'Pelzer, Dave',
 'Donaldson, Julia',
 'McCourt, Frank',
 'Faulks, Sebastian',
 'Pullman, Philip',
 'Mosse, Kate',
 'Rowling, J.K.',
 'Stockett, Kathryn',
 'Parsons, Tony',
 'Golden, Arthur',
 'McCall Smith, Alexander',
 'Hislop, Victoria',
 'Ahern, Cecelia',
 'McKeith, Gillian',
 'Zafon, Carlos Ruiz',
 'Rowling, J.K.',
 'Grisham, John',
 'Atkins, Robert C.',
 'Pullman, Philip',
 'Truss, Lynne',
 'Smith, Delia',
 'Harris, Joanne',
 'Boyne, John',
 'Picoult, Jodi',
 'Pullman, Philip',
 'Lee, Harper',
 'Gray, John',
 'French, Dawn',
 'Lewycka, Marina',
 'Harris, Thomas',
 'Tolkien, J. R. R.',
 'Moore, Michael',
 'Rubenfeld, Jed',
 'Osbourne, Sharon',
 'Coelho, Paulo',
 "O'Grady, Paul",
 'Bryson, Bill',
 'Oliver, Jamie',
 'Fielding, Helen',
 'Oliver, Jamie',
 'McKenna, Paul',
 'Bryson, Bill',
 'Grisham, John',
 'Levy, Andrea',
 'Lawson, Nigella',
 'Ali, Monica',
 'Edwards, Kim',
 'Donaldson, Julia',
 'Hornby, Nick',
 'Brand, Russell',
 'Dawkins, Richard',
 '0',
 'Smith, Zadie',
 'Morton, Kate',
 'Zusak, Markus',
 'Binchy, Maeve',
 'Harris, Robert',
 'Oliver, Jamie',
 'Collins, Suzanne',
 'Pelzer, Dave',
 'Oliver, Jamie']

In [8]:
vol=[]
for i in range(1,101):        
    vol_tags=driver.find_element_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{}]/td[4]".format(i))
    vol.append(vol_tags.text)

In [9]:
vol

['5,094,805',
 '4,475,152',
 '4,200,654',
 '4,179,479',
 '3,758,936',
 '3,583,215',
 '3,484,047',
 '3,377,906',
 '3,193,946',
 '2,950,264',
 '2,479,784',
 '2,315,405',
 '2,233,570',
 '2,193,928',
 '2,183,031',
 '2,152,737',
 '2,062,145',
 '2,052,876',
 '2,005,598',
 '1,979,552',
 '1,928,900',
 '1,852,919',
 '1,814,784',
 '1,787,118',
 '1,783,535',
 '1,781,269',
 '1,743,266',
 '1,629,119',
 '1,616,068',
 '1,583,992',
 '1,555,135',
 '1,546,886',
 '1,539,428',
 '1,508,205',
 '1,489,403',
 '1,352,318',
 '1,310,207',
 '1,310,176',
 '1,231,957',
 '1,217,712',
 '1,208,711',
 '1,204,058',
 '1,184,967',
 '1,181,503',
 '1,181,093',
 '1,153,181',
 '1,132,336',
 '1,130,802',
 '1,126,337',
 '1,115,549',
 '1,108,328',
 '1,107,379',
 '1,104,403',
 '1,092,349',
 '1,090,847',
 '1,087,262',
 '1,054,196',
 '1,037,160',
 '1,023,688',
 '1,015,956',
 '1,009,873',
 '1,004,414',
 '1,003,780',
 '1,002,314',
 '998,213',
 '992,846',
 '986,753',
 '986,115',
 '970,509',
 '967,466',
 '963,353',
 '962,515',
 '959,496',
 '956,114',
 '945,640',
 '931,312',
 '925,425',
 '924,695',
 '906,968',
 '905,086',
 '890,847',
 '869,671',
 '869,659',
 '862,602',
 '856,540',
 '845,858',
 '842,535',
 '828,215',
 '820,563',
 '816,907',
 '816,585',
 '815,586',
 '814,370',
 '809,641',
 '808,900',
 '807,311',
 '794,201',
 '792,187',
 '791,507',
 '791,095']

In [10]:
publisher=[]
for i in range(1,101):        
    publisher_tags=driver.find_element_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{}]/td[5]".format(i))
    publisher.append(publisher_tags.text)

In [15]:
publisher

['Transworld',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Random House',
 'Bloomsbury',
 'Bloomsbury',
 'Bloomsbury',
 'Transworld',
 'Bloomsbury',
 'Random House',
 'Little, Brown Book',
 'Quercus',
 'Random House',
 'Transworld',
 'Little, Brown Book',
 'Transworld',
 'Little, Brown Book',
 'Pan Macmillan',
 'Random House',
 'Transworld',
 'Transworld',
 'Quercus',
 'Little, Brown Book',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Bloomsbury',
 'Hodder & Stoughton',
 'Bloomsbury',
 'Quercus',
 'Random House',
 'Random House',
 'Pan Macmillan',
 'Penguin',
 'Random House',
 'Random House',
 'Canongate',
 'HarperCollins',
 'Orion',
 'Pan Macmillan',
 'HarperCollins',
 'Random House',
 'Scholastic Ltd.',
 'Orion',
 'Bloomsbury',
 'Penguin',
 'HarperCollins',
 'Random House',
 'Little, Brown Book',
 'Headline',
 'HarperCollins',
 'Penguin',
 'Orion',
 'Bloomsbury',
 'Random House',
 'Random House',
 'Scholastic Ltd.',
 'Profile Books Group',
 'Random House',
 'Transworld',
 'Random House Childrens Books G',
 'Hodder & Stoughton',
 'Scholastic Ltd.',
 'Random House',
 'HarperCollins',
 'Random House',
 'Penguin',
 'Random House',
 'HarperCollins',
 'Penguin',
 'Headline',
 'Little, Brown Book',
 'HarperCollins',
 'Transworld',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Transworld',
 'Transworld',
 'Random House',
 'Headline',
 'Random House',
 'Transworld',
 'Penguin',
 'Pan Macmillan',
 'Penguin',
 'Hodder & Stoughton',
 'Transworld',
 'D.C. Thomson',
 'Penguin',
 'Pan Macmillan',
 'Transworld',
 'Orion',
 'Random House',
 'Penguin',
 'Scholastic Ltd.',
 'Orion',
 'Penguin']

In [16]:
genre=[]
for i in range(1,101):        
    genre_tags=driver.find_element_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{}]/td[6]".format(i))
    genre.append(genre_tags.text)

In [18]:
genre

['Crime, Thriller & Adventure',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Romance & Sagas',
 "Children's Fiction",
 "Children's Fiction",
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 "Children's Fiction",
 'Romance & Sagas',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Romance & Sagas',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Popular Science',
 'Crime, Thriller & Adventure',
 'Young Adult Fiction',
 'Picture Books',
 'Picture Books',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Humour: Collections & General',
 'General & Literary Fiction',
 'Autobiography: General',
 'General & Literary Fiction',
 'Biography: The Arts',
 'Autobiography: General',
 'Picture Books',
 'Autobiography: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Science Fiction & Fantasy',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Fitness & Diet',
 'General & Literary Fiction',
 "Children's Fiction",
 'Crime, Thriller & Adventure',
 'Fitness & Diet',
 'Young Adult Fiction',
 'Usage & Writing Guides',
 'Food & Drink: General',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Young Adult Fiction',
 'General & Literary Fiction',
 'Popular Culture & Media: General Interest',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Crime, Thriller & Adventure',
 'Science Fiction & Fantasy',
 'Current Affairs & Issues',
 'Crime, Thriller & Adventure',
 'Autobiography: The Arts',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Travel Writing',
 'Food & Drink: General',
 'General & Literary Fiction',
 'National & Regional Cuisine',
 'Fitness & Diet',
 'Travel Writing',
 'Crime, Thriller & Adventure',
 'General & Literary Fiction',
 'Food & Drink: General',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Picture Books',
 'General & Literary Fiction',
 'Autobiography: The Arts',
 'Popular Science',
 "Children's Annuals",
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'General & Literary Fiction',
 'Food & Drink: General',
 'Young Adult Fiction',
 'Biography: General',
 'Food & Drink: General']

In [19]:
Novel=pd.DataFrame({})
Novel["Book name"]=title
Novel["Author name"]=author
Novel["Volumes sold"]=vol
Novel["Publisher"]=publisher
Novel["Genre"]=genre

In [20]:
Novel

,Book name,Author name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# 9. Scrape the details most watched tv series of all time from imdb.com.
# Url = https://www.imdb.com/list/ls095964455/
# You have to find the following details:
# A) Name
# B) Year span
# C) Genre
# D) Run time
# E) Ratings
# F) Votes

In [21]:
driver = webdriver.Chrome(r"C:\Data Science\Flip Robo\Selenium\chromedriver_win32\chromedriver.exe")

In [22]:
url = "https://www.imdb.com/list/ls095964455/"
driver.get(url)
driver.maximize_window()

In [32]:
title_tags = driver.find_elements_by_xpath("//h3[@class='lister-item-header']//a")

In [33]:
title=[]
for i in title_tags:
     title.append(i.text)

In [34]:
title

['Game of Thrones',
 'Stranger Things',
 'The Walking Dead',
 '13 Reasons Why',
 'The 100',
 'Orange Is the New Black',
 'Riverdale',
 "Grey's Anatomy",
 'The Flash',
 'Arrow',
 'Money Heist',
 'The Big Bang Theory',
 'Black Mirror',
 'Sherlock',
 'Vikings',
 'Pretty Little Liars',
 'The Vampire Diaries',
 'American Horror Story',
 'Breaking Bad',
 'Lucifer',
 'Supernatural',
 'Prison Break',
 'How to Get Away with Murder',
 'Teen Wolf',
 'The Simpsons',
 'Once Upon a Time',
 'Narcos',
 'Daredevil',
 'Friends',
 'How I Met Your Mother',
 'Suits',
 'Mr. Robot',
 'The Originals',
 'Supergirl',
 'Gossip Girl',
 'Sense8',
 'Gotham',
 'Westworld',
 'Jessica Jones',
 'Modern Family',
 'Rick and Morty',
 'Shadowhunters',
 'The End of the F***ing World',
 'House of Cards',
 'Dark',
 'Elite',
 'Sex Education',
 'Shameless',
 'New Girl',
 'Agents of S.H.I.E.L.D.',
 'You',
 'Dexter',
 'Fear the Walking Dead',
 'Family Guy',
 'The Blacklist',
 'Lost',
 'Peaky Blinders',
 'House',
 'Quantico',
 'Orphan Black',
 'Homeland',
 'Blindspot',
 "DC's Legends of Tomorrow",
 "The Handmaid's Tale",
 'Chilling Adventures of Sabrina',
 'The Good Doctor',
 'Jane the Virgin',
 'Glee',
 'South Park',
 'Brooklyn Nine-Nine',
 'Under the Dome',
 'The Umbrella Academy',
 'True Detective',
 'The OA',
 'Desperate Housewives',
 'Better Call Saul',
 'Bates Motel',
 'The Punisher',
 'Atypical',
 'Dynasty',
 'This Is Us',
 'The Good Place',
 'Iron Fist',
 'The Rain',
 'Mindhunter',
 'Revenge',
 'Luke Cage',
 'Scandal',
 'The Defenders',
 'Big Little Lies',
 'Insatiable',
 'The Mentalist',
 'The Crown',
 'Chernobyl',
 'iZombie',
 'Reign',
 'A Series of Unfortunate Events',
 'Criminal Minds',
 'Scream: The TV Series',
 'The Haunting of Hill House']

In [38]:
year_tags = driver.find_elements_by_xpath("//h3[@class='lister-item-header']//span[@class='lister-item-year text-muted unbold']")

In [39]:
year=[]
for i in year_tags:
     year.append(i.text.replace("(",'').replace(")",''))

In [44]:
year

['2011–2019',
 '2016– ',
 '2010–2022',
 '2017–2020',
 '2014–2020',
 '2013–2019',
 '2017– ',
 '2005– ',
 '2014– ',
 '2012–2020',
 '2017–2021',
 '2007–2019',
 '2011– ',
 '2010–2017',
 '2013–2020',
 '2010–2017',
 '2009–2017',
 '2011– ',
 '2008–2013',
 '2016– ',
 '2005–2020',
 '2005–2017',
 '2014–2020',
 '2011–2017',
 '1989– ',
 '2011–2018',
 '2015–2017',
 '2015–2018',
 '1994–2004',
 '2005–2014',
 '2011–2019',
 '2015–2019',
 '2013–2018',
 '2015–2021',
 '2007–2012',
 '2015–2018',
 '2014–2019',
 '2016– ',
 '2015–2019',
 '2009–2020',
 '2013– ',
 '2016–2019',
 '2017–2019',
 '2013–2018',
 '2017–2020',
 '2018– ',
 '2019– ',
 '2011–2021',
 '2011–2018',
 '2013–2020',
 '2018– ',
 '2006–2021',
 '2015– ',
 '1999–2022',
 '2013– ',
 '2004–2010',
 '2013– ',
 '2004–2012',
 '2015–2018',
 '2013–2017',
 '2011–2020',
 '2015–2020',
 '2016– ',
 '2017– ',
 '2018–2020',
 '2017– ',
 '2014–2019',
 '2009–2015',
 '1997– ',
 '2013–2022',
 '2013–2015',
 '2019– ',
 '2014–2019',
 '2016–2019',
 '2004–2012',
 '2015– ',
 '2013–2017',
 '2017–2019',
 '2017–2021',
 '2017– ',
 '2016–2022',
 '2016–2020',
 '2017–2018',
 '2018–2020',
 '2017–2019',
 '2011–2015',
 '2016–2018',
 '2012–2018',
 '2017',
 '2017–2019',
 '2018–2019',
 '2008–2015',
 '2016– ',
 '2019',
 '2015–2019',
 '2013–2017',
 '2017–2019',
 '2005–2020',
 '2015–2019',
 '2018']

In [45]:
genre_tags = driver.find_elements_by_xpath("//span[@class='genre']")

In [46]:
genre=[]
for i in genre_tags:
     genre.append(i.text)

In [48]:
genre

['Action, Adventure, Drama',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Thriller',
 'Drama, Mystery, Thriller',
 'Drama, Mystery, Sci-Fi',
 'Comedy, Crime, Drama',
 'Crime, Drama, Mystery',
 'Drama, Romance',
 'Action, Adventure, Drama',
 'Action, Adventure, Crime',
 'Action, Crime, Mystery',
 'Comedy, Romance',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Mystery',
 'Action, Adventure, Drama',
 'Drama, Mystery, Romance',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Thriller',
 'Crime, Drama, Thriller',
 'Crime, Drama, Fantasy',
 'Drama, Fantasy, Horror',
 'Action, Crime, Drama',
 'Crime, Drama, Mystery',
 'Action, Drama, Fantasy',
 'Animation, Comedy',
 'Adventure, Fantasy, Romance',
 'Biography, Crime, Drama',
 'Action, Crime, Drama',
 'Comedy, Romance',
 'Comedy, Romance',
 'Comedy, Drama',
 'Crime, Drama, Thriller',
 'Drama, Fantasy, Horror',
 'Action, Adventure, Drama',
 'Drama, Romance',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Drama, Mystery, Sci-Fi',
 'Action, Crime, Drama',
 'Comedy, Drama, Romance',
 'Animation, Adventure, Comedy',
 'Action, Drama, Fantasy',
 'Adventure, Comedy, Crime',
 'Drama',
 'Crime, Drama, Mystery',
 'Crime, Drama, Thriller',
 'Comedy, Drama',
 'Comedy, Drama',
 'Comedy',
 'Action, Adventure, Drama',
 'Crime, Drama, Romance',
 'Crime, Drama, Mystery',
 'Drama, Horror, Sci-Fi',
 'Animation, Comedy',
 'Crime, Drama, Mystery',
 'Adventure, Drama, Fantasy',
 'Crime, Drama',
 'Drama, Mystery',
 'Crime, Drama, Mystery',
 'Action, Drama, Sci-Fi',
 'Crime, Drama, Mystery',
 'Action, Crime, Drama',
 'Action, Adventure, Drama',
 'Drama, Sci-Fi, Thriller',
 'Drama, Fantasy, Horror',
 'Drama',
 'Comedy',
 'Comedy, Drama, Music',
 'Animation, Comedy',
 'Comedy, Crime',
 'Drama, Mystery, Sci-Fi',
 'Action, Adventure, Comedy',
 'Crime, Drama, Mystery',
 'Drama, Fantasy, Mystery',
 'Comedy, Drama, Mystery',
 'Crime, Drama',
 'Drama, Horror, Mystery',
 'Action, Crime, Drama',
 'Comedy, Drama',
 'Drama',
 'Comedy, Drama, Romance',
 'Comedy, Drama, Fantasy',
 'Action, Adventure, Crime',
 'Drama, Sci-Fi, Thriller',
 'Crime, Drama, Thriller',
 'Drama, Mystery, Thriller',
 'Action, Crime, Drama',
 'Drama, Thriller',
 'Action, Adventure, Crime',
 'Crime, Drama, Mystery',
 'Comedy, Drama, Thriller',
 'Crime, Drama, Mystery',
 'Biography, Drama, History',
 'Drama, History, Thriller',
 'Comedy, Crime, Drama',
 'Drama, Fantasy',
 'Adventure, Comedy, Drama',
 'Crime, Drama, Mystery',
 'Comedy, Crime, Drama',
 'Drama, Horror, Mystery']

In [49]:
run_time_tags = driver.find_elements_by_xpath("//span[@class='runtime']")

In [50]:
run_time=[]
for i in run_time_tags:
     run_time.append(i.text)

In [52]:
run_time

['57 min',
 '51 min',
 '44 min',
 '60 min',
 '43 min',
 '59 min',
 '45 min',
 '41 min',
 '43 min',
 '42 min',
 '70 min',
 '22 min',
 '60 min',
 '88 min',
 '44 min',
 '44 min',
 '43 min',
 '60 min',
 '49 min',
 '42 min',
 '44 min',
 '44 min',
 '43 min',
 '41 min',
 '22 min',
 '60 min',
 '49 min',
 '54 min',
 '22 min',
 '22 min',
 '44 min',
 '49 min',
 '45 min',
 '43 min',
 '42 min',
 '60 min',
 '42 min',
 '62 min',
 '56 min',
 '22 min',
 '23 min',
 '42 min',
 '25 min',
 '51 min',
 '60 min',
 '60 min',
 '45 min',
 '46 min',
 '22 min',
 '45 min',
 '45 min',
 '53 min',
 '44 min',
 '22 min',
 '43 min',
 '44 min',
 '60 min',
 '44 min',
 '42 min',
 '44 min',
 '55 min',
 '42 min',
 '42 min',
 '60 min',
 '60 min',
 '41 min',
 '60 min',
 '44 min',
 '22 min',
 '22 min',
 '43 min',
 '60 min',
 '55 min',
 '60 min',
 '45 min',
 '46 min',
 '45 min',
 '53 min',
 '30 min',
 '42 min',
 '45 min',
 '22 min',
 '55 min',
 '45 min',
 '60 min',
 '44 min',
 '55 min',
 '43 min',
 '50 min',
 '60 min',
 '45 min',
 '43 min',
 '58 min',
 '330 min',
 '42 min',
 '42 min',
 '50 min',
 '42 min',
 '45 min',
 '572 min']

In [60]:
ratings_tags = driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']//span[@class='ipl-rating-star__rating']")

In [61]:
len(ratings_tags)

100

In [62]:
ratings=[]
for i in ratings_tags:
     ratings.append(i.text)

In [63]:
ratings

['9.2',
 '8.7',
 '8.2',
 '7.6',
 '7.6',
 '8',
 '6.8',
 '7.5',
 '7.6',
 '7.5',
 '8.3',
 '8.1',
 '8.8',
 '9.1',
 '8.5',
 '7.4',
 '7.7',
 '8',
 '9.4',
 '8.1',
 '8.4',
 '8.3',
 '8.1',
 '7.6',
 '8.6',
 '7.7',
 '8.8',
 '8.6',
 '8.9',
 '8.3',
 '8.4',
 '8.5',
 '8.2',
 '6.2',
 '7.4',
 '8.3',
 '7.8',
 '8.6',
 '7.9',
 '8.4',
 '9.2',
 '6.6',
 '8.1',
 '8.7',
 '8.8',
 '7.5',
 '8.3',
 '8.5',
 '7.7',
 '7.5',
 '7.7',
 '8.6',
 '6.9',
 '8.1',
 '8',
 '8.3',
 '8.8',
 '8.7',
 '6.7',
 '8.3',
 '8.3',
 '7.4',
 '6.8',
 '8.4',
 '7.5',
 '8.1',
 '7.8',
 '6.7',
 '8.7',
 '8.4',
 '6.6',
 '8',
 '8.9',
 '7.8',
 '7.5',
 '8.8',
 '8.1',
 '8.5',
 '8.3',
 '7.3',
 '8.7',
 '8.2',
 '6.5',
 '6.3',
 '8.6',
 '7.8',
 '7.3',
 '7.7',
 '7.3',
 '8.5',
 '6.5',
 '8.1',
 '8.6',
 '9.4',
 '7.8',
 '7.5',
 '7.8',
 '8.1',
 '7.1',
 '8.6']

In [64]:
votes_tags = driver.find_elements_by_xpath("//span[@name='nv']")

In [66]:
votes=[]
for i in votes_tags:
     votes.append(i.text)

In [67]:
votes

['1,835,093',
 '873,855',
 '879,184',
 '264,169',
 '225,682',
 '283,502',
 '125,048',
 '263,601',
 '316,868',
 '413,401',
 '337,262',
 '740,358',
 '465,924',
 '834,576',
 '455,434',
 '155,212',
 '292,012',
 '283,939',
 '1,539,023',
 '258,657',
 '401,712',
 '490,056',
 '135,155',
 '132,007',
 '373,681',
 '211,922',
 '372,954',
 '372,807',
 '872,241',
 '621,055',
 '372,656',
 '343,876',
 '121,850',
 '114,737',
 '158,504',
 '143,410',
 '215,543',
 '442,029',
 '197,072',
 '373,999',
 '404,427',
 '55,770',
 '156,063',
 '474,985',
 '309,186',
 '57,859',
 '174,403',
 '212,094',
 '199,257',
 '204,275',
 '155,703',
 '661,161',
 '117,290',
 '311,098',
 '210,776',
 '509,631',
 '386,561',
 '424,282',
 '57,991',
 '103,900',
 '321,228',
 '67,970',
 '95,148',
 '191,869',
 '81,877',
 '68,537',
 '41,200',
 '139,323',
 '338,429',
 '245,435',
 '102,389',
 '173,284',
 '512,885',
 '94,098',
 '119,176',
 '344,398',
 '99,756',
 '192,990',
 '66,278',
 '16,397',
 '115,434',
 '125,719',
 '118,085',
 '32,575',
 '233,071',
 '114,461',
 '119,532',
 '68,459',
 '93,907',
 '166,628',
 '23,871',
 '169,464',
 '167,910',
 '589,104',
 '61,900',
 '44,783',
 '55,389',
 '169,542',
 '35,118',
 '193,318']

In [68]:
TV_Series=pd.DataFrame({})
TV_Series["Name of the series"]=title
TV_Series["Year span"]=year
TV_Series["Genre"]=genre
TV_Series["Run time"]=run_time
TV_Series["Ratings"]=ratings
TV_Series["Votes"]=votes

In [69]:
TV_Series

,Name of the series,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,2011–2019,"Action, Adventure, Drama",57 min,9.2,"1,835,093"
1,Stranger Things,2016–,"Drama, Fantasy, Horror",51 min,8.7,"873,855"
2,The Walking Dead,2010–2022,"Drama, Horror, Thriller",44 min,8.2,"879,184"
3,13 Reasons Why,2017–2020,"Drama, Mystery, Thriller",60 min,7.6,"264,169"
4,The 100,2014–2020,"Drama, Mystery, Sci-Fi",43 min,7.6,"225,682"
...,...,...,...,...,...,...
95,Reign,2013–2017,"Drama, Fantasy",42 min,7.5,"44,783"
96,A Series of Unfortunate Events,2017–2019,"Adventure, Comedy, Drama",50 min,7.8,"55,389"
97,Criminal Minds,2005–2020,"Crime, Drama, Mystery",42 min,8.1,"169,542"
98,Scream: The TV Series,2015–2019,"Comedy, Crime, Drama",45 min,7.1,"35,118"
99,The Haunting of Hill House,2018,"Drama, Horror, Mystery",572 min,8.6,"193,318"

# 10. Details of Datasets from UCI machine learning repositories.
# Url = https://archive.ics.uci.edu/
# You have to find the following details:
# A) Dataset name
# B) Data type
# C) Task
# D) Attribute type
# E) No of instances
# F) No of attribute
# G) Year
# Note: - from the home page you have to go to the Show All Dataset page through code.

In [70]:
driver = webdriver.Chrome(r"C:\Data Science\Flip Robo\Selenium\chromedriver_win32\chromedriver.exe")

In [71]:
url = "https://archive.ics.uci.edu/ml/index.php"
driver.get(url)
driver.maximize_window()

In [77]:
urls=[]

In [79]:
dataset_url = driver.find_element_by_xpath('/html/body/table[1]/tbody/tr/td[2]/span[2]/a')
urls.append(dataset_url.get_attribute('href'))

In [80]:
urls

['https://archive.ics.uci.edu/ml/datasets.php']

In [81]:
for b in urls:
    driver.get(b)

In [112]:
name=[]
for i in range(2,590):        
    name_tags=driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{}]/td[1]/table/tbody/tr/td[2]/p/b/a".format(i))
    name.append(name_tags.text)

In [126]:
name

['Abalone',
 'Adult',
 'Annealing',
 'Anonymous Microsoft Web Data',
 'Arrhythmia',
 'Artificial Characters',
 'Audiology (Original)',
 'Audiology (Standardized)',
 'Auto MPG',
 'Automobile',
 'Badges',
 'Balance Scale',
 'Balloons',
 'Breast Cancer',
 'Breast Cancer Wisconsin (Original)',
 'Breast Cancer Wisconsin (Prognostic)',
 'Breast Cancer Wisconsin (Diagnostic)',
 'Pittsburgh Bridges',
 'Car Evaluation',
 'Census Income',
 'Chess (King-Rook vs. King-Knight)',
 'Chess (King-Rook vs. King-Pawn)',
 'Chess (King-Rook vs. King)',
 'Chess (Domain Theories)',
 'Bach Chorales',
 'Connect-4',
 'Credit Approval',
 'Japanese Credit Screening',
 'Computer Hardware',
 'Contraceptive Method Choice',
 'Covertype',
 'Cylinder Bands',
 'Dermatology',
 'Diabetes',
 'DGP2 - The Second Data Generation Program',
 'Document Understanding',
 'EBL Domain Theories',
 'Echocardiogram',
 'Ecoli',
 'Flags',
 'Function Finding',
 'Glass Identification',
 "Haberman's Survival",
 'Hayes-Roth',
 'Heart Disease',
 'Hepatitis',
 'Horse Colic',
 'ICU',
 'Image Segmentation',
 'Internet Advertisements',
 'Ionosphere',
 'Iris',
 'ISOLET',
 'Kinship',
 'Labor Relations',
 'LED Display Domain',
 'Lenses',
 'Letter Recognition',
 'Liver Disorders',
 'Logic Theorist',
 'Lung Cancer',
 'Lymphography',
 'Mechanical Analysis',
 'Meta-data',
 'Mobile Robots',
 'Molecular Biology (Promoter Gene Sequences)',
 'Molecular Biology (Protein Secondary Structure)',
 'Molecular Biology (Splice-junction Gene Sequences)',
 "MONK's Problems",
 'Moral Reasoner',
 'Multiple Features',
 'Mushroom',
 'Musk (Version 1)',
 'Musk (Version 2)',
 'Nursery',
 'Othello Domain Theory',
 'Page Blocks Classification',
 'Optical Recognition of Handwritten Digits',
 'Pen-Based Recognition of Handwritten Digits',
 'Post-Operative Patient',
 'Primary Tumor',
 'Prodigy',
 'Qualitative Structure Activity Relationships',
 'Quadruped Mammals',
 'Servo',
 'Shuttle Landing Control',
 'Solar Flare',
 'Soybean (Large)',
 'Soybean (Small)',
 'Challenger USA Space Shuttle O-Ring',
 'Low Resolution Spectrometer',
 'Spambase',
 'SPECT Heart',
 'SPECTF Heart',
 'Sponge',
 'Statlog Project',
 'Student Loan Relational',
 'Teaching Assistant Evaluation',
 'Tic-Tac-Toe Endgame',
 'Thyroid Disease',
 'Trains',
 'University',
 'Congressional Voting Records',
 'Water Treatment Plant',
 'Waveform Database Generator (Version 1)',
 'Waveform Database Generator (Version 2)',
 'Wine',
 'Yeast',
 'Zoo',
 'Undocumented',
 'Twenty Newsgroups',
 'Australian Sign Language signs',
 'Australian Sign Language signs (High Quality)',
 'US Census Data (1990)',
 'Census-Income (KDD)',
 'Coil 1999 Competition Data',
 'Corel Image Features',
 'E. Coli Genes',
 'EEG Database',
 'El Nino',
 'Entree Chicago Recommendation Data',
 'CMU Face Images',
 'Insurance Company Benchmark (COIL 2000)',
 'Internet Usage Data',
 'IPUMS Census Database',
 'Japanese Vowels',
 'KDD Cup 1998 Data',
 'KDD Cup 1999 Data',
 'M. Tuberculosis Genes',
 'Movie',
 'MSNBC.com Anonymous Web Data',
 'NSF Research Award Abstracts 1990-2003',
 'Pioneer-1 Mobile Robot Data',
 'Pseudo Periodic Synthetic Time Series',
 'Reuters-21578 Text Categorization Collection',
 'Robot Execution Failures',
 'Synthetic Control Chart Time Series',
 'Syskill and Webert Web Page Ratings',
 'UNIX User Data',
 'Volcanoes on Venus - JARtool experiment',
 'Statlog (Australian Credit Approval)',
 'Statlog (German Credit Data)',
 'Statlog (Heart)',
 'Statlog (Landsat Satellite)',
 'Statlog (Image Segmentation)',
 'Statlog (Shuttle)',
 'Statlog (Vehicle Silhouettes)',
 'Connectionist Bench (Nettalk Corpus)',
 'Connectionist Bench (Sonar, Mines vs. Rocks)',
 'Connectionist Bench (Vowel Recognition - Deterding Data)',
 'Economic Sanctions',
 'Protein Data',
 'Cloud',
 'CalIt2 Building People Counts',
 'Dodgers Loop Sensor',
 'Poker Hand',
 'MAGIC Gamma Telescope',
 'UJI Pen Characters',
 'Mammographic Mass',
 'Forest Fires',
 'Reuters Transcribed Subset',
 'Bag of Words',
 'Concrete Compressive Strength',
 'Hill-Valley',
 'Arcene',
 'Dexter',
 'Dorothea',
 'Gisette',
 'Madelon',
 'Ozone Level Detection',
 'Abscisic Acid Signaling Network',
 'Parkinsons',
 'Character Trajectories',
 'Blood Transfusion Service Center',
 'UJI Pen Characters (Version 2)',
 'Semeion Handwritten Digit',
 'SECOM',
 'Plants',
 'Libras Movement',
 'Concrete Slump Test',
 'Communities and Crime',
 'Acute Inflammations',
 'Wine Quality',
 'URL Reputation',
 'p53 Mutants',
 'Parkinsons Telemonitoring',
 'Demospongiae',
 'Opinosis Opinion ⁄ Review',
 'Breast Tissue',
 'Cardiotocography',
 'Wall-Following Robot Navigation Data',
 'Spoken Arabic Digit',
 'Localization Data for Person Activity',
 'AutoUniv',
 'Steel Plates Faults',
 'MiniBooNE particle identification',
 'YearPredictionMSD',
 'PEMS-SF',
 'OpinRank Review Dataset',
 'Relative location of CT slices on axial axis',
 'Online Handwritten Assamese Characters Dataset',
 'PubChem Bioassay Data',
 'Record Linkage Comparison Patterns',
 'Communities and Crime Unnormalized',
 'Vertebral Column',
 'EMG Physical Action Data Set',
 'Vicon Physical Action Data Set',
 'Amazon Commerce reviews set',
 'Amazon Access Samples',
 'Reuter_50_50',
 'Farm Ads',
 'DBWorld e-mails',
 'KEGG Metabolic Relation Network (Directed)',
 'KEGG Metabolic Reaction Network (Undirected)',
 'Bank Marketing',
 'YouTube Comedy Slam Preference Data',
 'Gas Sensor Array Drift Dataset',
 'ILPD (Indian Liver Patient Dataset)',
 'OPPORTUNITY Activity Recognition',
 'Nomao',
 'SMS Spam Collection',
 'Skin Segmentation',
 'Planning Relax',
 'PAMAP2 Physical Activity Monitoring',
 'Restaurant & consumer data',
 'CNAE-9',
 'Individual household electric power consumption',
 'seeds',
 'Northix',
 'QtyT40I10D100K',
 'Legal Case Reports',
 'Human Activity Recognition Using Smartphones',
 'One-hundred plant species leaves data set',
 'Energy efficiency',
 'Yacht Hydrodynamics',
 'Fertility',
 'Daphnet Freezing of Gait',
 '3D Road Network (North Jutland, Denmark)',
 'ISTANBUL STOCK EXCHANGE',
 'Buzz in social media',
 'First-order theorem proving',
 'Wearable Computing: Classification of Body Postures and Movements (PUC-Rio)',
 'Gas sensor arrays in open sampling settings',
 'Climate Model Simulation Crashes',
 'MicroMass',
 'QSAR biodegradation',
 'BLOGGER',
 'Daily and Sports Activities',
 'User Knowledge Modeling',
 'Reuters RCV1 RCV2 Multilingual, Multiview Text Categorization Test collection',
 'NYSK',
 'Turkiye Student Evaluation',
 "ser Knowledge Modeling Data (Students' Knowledge Levels on DC Electrical Machines)",
 'EEG Eye State',
 'Physicochemical Properties of Protein Tertiary Structure',
 'seismic-bumps',
 'banknote authentication',
 'USPTO Algorithm Challenge, run by NASA-Harvard Tournament Lab and TopCoder Problem: Pat',
 'YouTube Multiview Video Games Dataset',
 'Gas Sensor Array Drift Dataset at Different Concentrations',
 'Activities of Daily Living (ADLs) Recognition Using Binary Sensors',
 'SkillCraft1 Master Table Dataset',
 'Weight Lifting Exercises monitored with Inertial Measurement Units',
 'SML2010',
 'Bike Sharing Dataset',
 'Predict keywords activities in a online social media',
 'Thoracic Surgery Data',
 'EMG dataset in Lower Limb',
 'SUSY',
 'HIGGS',
 'Qualitative_Bankruptcy',
 'LSVT Voice Rehabilitation',
 'Dataset for ADL Recognition with Wrist-worn Accelerometer',
 'Wilt',
 'User Identification From Walking Activity',
 'Activity Recognition from Single Chest-Mounted Accelerometer',
 'Leaf',
 'Dresses_Attribute_Sales',
 'Tamilnadu Electricity Board Hourly Readings',
 'Airfoil Self-Noise',
 'Wholesale customers',
 'Twitter Data set for Arabic Sentiment Analysis',
 'Combined Cycle Power Plant',
 'Urban Land Cover',
 'Diabetes 130-US hospitals for years 1999-2008',
 'Bach Choral Harmony',
 'StoneFlakes',
 'Tennis Major Tournament Match Statistics',
 'Parkinson Speech Dataset with Multiple Types of Sound Recordings',
 'Gesture Phase Segmentation',
 'Perfume Data',
 'BlogFeedback',
 'REALDISP Activity Recognition Dataset',
 'Newspaper and magazine images segmentation dataset',
 'AAAI 2014 Accepted Papers',
 'Gas sensor array under flow modulation',
 'Gas sensor array exposed to turbulent gas mixtures',
 'UJIIndoorLoc',
 'Sentence Classification',
 'Dow Jones Index',
 'sEMG for Basic Hand movements',
 'AAAI 2013 Accepted Papers',
 'Geographical Original of Music',
 'Condition Based Maintenance of Naval Propulsion Plants',
 'Grammatical Facial Expressions',
 'NoisyOffice',
 'MHEALTH Dataset',
 'Student Performance',
 'ElectricityLoadDiagrams20112014',
 'Gas sensor array under dynamic gas mixtures',
 'microblogPCU',
 'Firm-Teacher_Clave-Direction_Classification',
 'Dataset for Sensorless Drive Diagnosis',
 'TV News Channel Commercial Detection Dataset',
 'Phishing Websites',
 'Greenhouse Gas Observing Network',
 'Diabetic Retinopathy Debrecen Data Set',
 'HIV-1 protease cleavage',
 'Sentiment Labelled Sentences',
 'Online News Popularity',
 'Forest type mapping',
 'wiki4HE',
 'Online Video Characteristics and Transcoding Time Dataset',
 'Chronic_Kidney_Disease',
 'Machine Learning based ZZAlpha Ltd. Stock Recommendations 2012-2014',
 'Folio',
 'Taxi Service Trajectory - Prediction Challenge, ECML PKDD 2015',
 'Cuff-Less Blood Pressure Estimation',
 'Smartphone-Based Recognition of Human Activities and Postural Transitions',
 'Mice Protein Expression',
 'UJIIndoorLoc-Mag',
 'Heterogeneity Activity Recognition',
 'Educational Process Mining (EPM): A Learning Analytics Data Set',
 'HEPMASS',
 'Indoor User Movement Prediction from RSS data',
 'Open University Learning Analytics dataset',
 'default of credit card clients',
 'Mesothelioma’s disease data set',
 'Online Retail',
 'SIFT10M',
 'GPS Trajectories',
 'Detect Malacious Executable(AntiVirus)',
 'Occupancy Detection',
 'Improved Spiral Test Using Digitized Graphics Tablet for Monitoring Parkinson’s Disease',
 'News Aggregator',
 'Air Quality',
 'Twin gas sensor arrays',
 'Gas sensors for home activity monitoring',
 'Facebook Comment Volume Dataset',
 'Smartphone Dataset for Human Activity Recognition (HAR) in Ambient Assisted Living (AAL)',
 'Polish companies bankruptcy data',
 'Activity Recognition system based on Multisensor data fusion (AReM)',
 'Dota2 Games Results',
 'Facebook metrics',
 'UbiqLog (smartphone lifelogging)',
 'NIPS Conference Papers 1987-2015',
 'HTRU2',
 'Drug consumption (quantified)',
 'Appliances energy prediction',
 'Miskolc IIS Hybrid IPS',
 'KDC-4007 dataset Collection',
 'Geo-Magnetic field and WLAN dataset for indoor localisation from wristband and smartphone',
 'DrivFace',
 'Website Phishing',
 'YouTube Spam Collection',
 'Beijing PM2.5 Data',
 'Cargo 2000 Freight Tracking and Tracing',
 'Cervical cancer (Risk Factors)',
 'Quality Assessment of Digital Colposcopies',
 'KASANDR',
 'FMA: A Dataset For Music Analysis',
 'Air quality',
 'Epileptic Seizure Recognition',
 'Devanagari Handwritten Character Dataset',
 'Stock portfolio performance',
 'MoCap Hand Postures',
 'Early biomarkers of Parkinson�s disease based on natural connected speech',
 'Data for Software Engineering Teamwork Assessment in Education Setting',
 'PM2.5 Data of Five Chinese Cities',
 'Parkinson Disease Spiral Drawings Using Digitized Graphics Tablet',
 'Sales_Transactions_Dataset_Weekly',
 'Las Vegas Strip',
 'Eco-hotel',
 'MEU-Mobile KSD',
 'Crowdsourced Mapping',
 'gene expression cancer RNA-Seq',
 'Hybrid Indoor Positioning Dataset from WiFi RSSI, Bluetooth and magnetometer',
 'chestnut – LARVIC',
 'Burst Header Packet (BHP) flooding attack on Optical Burst Switching (OBS) Network',
 'Motion Capture Hand Postures',
 'Anuran Calls (MFCCs)',
 'TTC-3600: Benchmark dataset for Turkish text categorization',
 'Gastrointestinal Lesions in Regular Colonoscopy',
 'Daily Demand Forecasting Orders',
 'Paper Reviews',
 'extention of Z-Alizadeh sani dataset',
 'Z-Alizadeh Sani',
 'Dynamic Features of VirusShare Executables',
 'IDA2016Challenge',
 'DSRC Vehicle Communications',
 'Mturk User-Perceived Clusters over Images',
 'Character Font Images',
 'DeliciousMIL: A Data Set for Multi-Label Multi-Instance Learning with Instance Labels',
 'Autistic Spectrum Disorder Screening Data for Children',
 'Autistic Spectrum Disorder Screening Data for Adolescent',
 'APS Failure at Scania Trucks',
 'Wireless Indoor Localization',
 'HCC Survival',
 'CSM (Conventional and Social Media Movies) Dataset 2014 and 2015',
 'University of Tehran Question Dataset 2016 (UTQD.2016)',
 'Autism Screening Adult',
 'Activity recognition with healthy older people using a batteryless wearable sensor',
 'Immunotherapy Dataset',
 'Cryotherapy Dataset',
 'OCT data & Color Fundus Images of Left & Right Eyes',
 'Discrete Tone Image Dataset',
 'News Popularity in Multiple Social Media Platforms',
 'Ultrasonic flowmeter diagnostics',
 'ICMLA 2014 Accepted Papers Data Set',
 'BLE RSSI Dataset for Indoor localization and Navigation',
 'Container Crane Controller Data Set',
 'Residential Building Data Set',
 'Health News in Twitter',
 'chipseq',
 'SGEMM GPU kernel performance',
 'Repeat Consumption Matrices',
 'detection_of_IoT_botnet_attacks_N_BaIoT',
 'Absenteeism at work',
 'SCADI',
 'Condition monitoring of hydraulic systems',
 'Carbon Nanotubes',
 'Optical Interconnection Network',
 'Sports articles for objectivity analysis',
 'Breast Cancer Coimbra',
 'GNFUV Unmanned Surface Vehicles Sensor Data',
 'Dishonest Internet users Dataset',
 'Victorian Era Authorship Attribution',
 'Simulated Falls and Daily Living Activities Data Set',
 'Multimodal Damage Identification for Humanitarian Computing',
 'EEG Steady-State Visual Evoked Potential Signals',
 'Roman Urdu Data Set',
 'Avila',
 'PANDOR',
 'Drug Review Dataset (Druglib.com)',
 'Drug Review Dataset (Drugs.com)',
 'Physical Unclonable Functions',
 'Superconductivty Data',
 'WESAD (Wearable Stress and Affect Detection)',
 'GNFUV Unmanned Surface Vehicles Sensor Data Set 2',
 'Student Academics Performance',
 'Online Shoppers Purchasing Intention Dataset',
 'PMU-UD',
 "Parkinson's Disease Classification",
 'Electrical Grid Stability Simulated Data',
 'Caesarian Section Classification Dataset',
 'BAUM-1',
 'BAUM-2',
 'Audit Data',
 'BuddyMove Data Set',
 'Real estate valuation data set',
 'Early biomarkers of Parkinson’s disease based on natural connected speech Data Set',
 'Somerville Happiness Survey',
 '2.4 GHZ Indoor Channel Measurements',
 'EMG data for gestures',
 'Parking Birmingham',
 'Behavior of the urban traffic of the city of Sao Paulo in Brazil',
 'Travel Reviews',
 'Tarvel Review Ratings',
 'Rice Leaf Diseases',
 'Gas sensor array temperature modulation',
 'Facebook Live Sellers in Thailand',
 'Parkinson Dataset with replicated acoustic features',
 'Metro Interstate Traffic Volume',
 'Query Analytics Workloads Dataset',
 'Wave Energy Converters',
 'PPG-DaLiA',
 'Alcohol QCM Sensor Dataset',
 'Divorce Predictors data set',
 'Incident management process enriched event log',
 'Opinion Corpus for Lebanese Arabic Reviews (OCLAR)',
 'MEx',
 'Beijing Multi-Site Air-Quality Data',
 'Online Retail II',
 'Hepatitis C Virus (HCV) for Egyptian patients',
 'QSAR fish toxicity',
 'QSAR aquatic toxicity',
 'Human Activity Recognition from Continuous Ambient Sensor Data',
 'WISDM Smartphone and Smartwatch Activity and Biometrics Dataset',
 'QSAR oral toxicity',
 'QSAR androgen receptor',
 'QSAR Bioconcentration classes dataset',
 'QSAR fish bioconcentration factor (BCF)',
 'A study of Asian Religious and Biblical Texts',
 'Real-time Election Results: Portugal 2019',
 'Bias correction of numerical prediction model temperature forecast',
 'Bar Crawl: Detecting Heavy Drinking',
 'Kitsune Network Attack Dataset',
 'Shoulder Implant X-Ray Manufacturer Classification',
 'Speaker Accent Recognition',
 'Heart failure clinical records',
 'Deepfakes: Medical Image Tamper Detection',
 'selfBACK',
 'South German Credit',
 'Exasens',
 'Swarm Behaviour',
 'Crop mapping using fused optical-radar data set',
 'BitcoinHeistRansomwareAddressDataset',
 'Facebook Large Page-Page Network',
 'Amphibians',
 'Early stage diabetes risk prediction dataset.',
 'Turkish Spam V01',
 'Stock keeping units',
 'Demand Forecasting for a store',
 'Detect Malware Types',
 'Wave Energy Converters',
 'Youtube cookery channels viewers comments in Hinglish',
 'Pedestrian in Traffic Dataset',
 'Cervical Cancer Behavior Risk',
 'Sattriya_Dance_Single_Hand_Gestures Dataset',
 'Divorce Predictors data set',
 '3W dataset',
 'Malware static and dynamic features VxHeaven and Virus Total',
 'Internet Firewall Data',
 'User Profiling and Abusive Language Detection Dataset',
 'Estimation of obesity levels based on eating habits and physical condition',
 'Rice (Cammeo and Osmancik)',
 'Vehicle routing and scheduling problems',
 'Algerian Forest Fires Dataset',
 'Breath Metabolomics',
 'Horton General Hospital',
 'UrbanGB, urban road accidents coordinates labelled by the urban center',
 'Gas Turbine CO and NOx Emission Data Set',
 'Activity recognition using wearable physiological measurements',
 'clickstream data for online shopping',
 'CNNpred: CNN-based stock market prediction using a diverse set of variables',
 'Apartment for rent classified',
 ': Simulated Data set of Iraqi tourism places',
 'Nasarian CAD Dataset',
 'Monolithic Columns in Troad and Mysia Region',
 'Bar Crawl: Detecting Heavy Drinking',
 'Seoul Bike Sharing Demand',
 'Person Classification Gait Data',
 'Shill Bidding Dataset',
 'Iranian Churn Dataset',
 'Unmanned Aerial Vehicle (UAV) Intrusion Detection',
 'Bone marrow transplant: children',
 'Exasens',
 'COVID-19 Surveillance',
 'Refractive errors',
 'Shoulder Implant X-Ray Manufacturer Classification',
 'CLINC150',
 'HCV data',
 'Taiwanese Bankruptcy Prediction',
 'South German Credit (UPDATE)',
 'IIWA14-R820-Gazebo-Dataset-10Trajectories',
 'Guitar Chords finger positions',
 'Russian Corpus of Biographical Texts',
 'Codon usage',
 'Intelligent Media Accelerometer and Gyroscope (IM-AccGyro) Dataset',
 'Myocardial infarction complications',
 'Hungarian Chickenpox Cases',
 'Simulated data for survival modelling',
 'Student Performance on an entrance examination',
 'Chemical Composition of Ceramic Samples',
 'Labeled Text Forum Threads Dataset',
 'Stock keeping units',
 'BLE RSSI dataset for Indoor localization',
 'Basketball dataset',
 'GitHub MUSAE',
 'Anticancer peptides',
 'Monolithic Columns in Troad and Mysia Region',
 'Gender by Name',
 'Iranian Churn Dataset',
 'Unmanned Aerial Vehicle (UAV) Intrusion Detection',
 'Shoulder Implant Manufacture Classification',
 'LastFM Asia Social Network',
 'Wheat kernels',
 'Productivity Prediction of Garment Employees',
 'Multi-view Brain Networks',
 'LastFM Asia Social Network',
 'Wisesight Sentiment Corpus',
 'AI4I 2020 Predictive Maintenance Dataset',
 'Dry Bean Dataset',
 'in-vehicle coupon recommendation',
 'Gait Classification',
 'Wikipedia Math Essentials',
 'Wikipedia Math Essentials',
 'Synchronous Machine Data Set']

In [143]:
len(name)

588

In [114]:
datatype=[]
for i in range(2,590):        
    datatype_tags=driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{}]/td[2]/p".format(i))
    if(datatype_tags.text!=' '):
        datatype.append(datatype_tags.text)
    else:
        datatype.append("None")

In [127]:
datatype

['Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'None',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Univariate, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Univariate, Time-Series ',
 'Multivariate, Spatial ',
 'Multivariate ',
 'Multivariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Data-Generator ',
 'None',
 'None',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'None',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Sequential, Domain-Theory ',
 'Sequential ',
 'Sequential, Domain-Theory ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Domain-Theory ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'None',
 'Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Data-Generator ',
 'Multivariate, Data-Generator ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'None',
 'Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate, Time-Series ',
 'Spatio-temporal ',
 'Transactional, Sequential ',
 'Image ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Relational ',
 'Multivariate, Relational ',
 'Sequential ',
 'Text ',
 'Multivariate, Time-Series ',
 'Univariate, Time-Series ',
 'Text ',
 'Multivariate, Time-Series ',
 'Time-Series ',
 'Multivariate, Text ',
 'Text, Sequential ',
 'Image ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'None',
 'Domain-Theory ',
 'None',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Text ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate, Time-Series ',
 'Univariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Text ',
 'Domain-Theory ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate, Text, Domain-Theory ',
 'Time-Series, Domain-Theory ',
 'Multivariate, Text, Domain-Theory ',
 'Text ',
 'Text ',
 'Multivariate, Univariate, Text ',
 'Multivariate, Univariate, Text ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate, Text, Domain-Theory ',
 'Univariate ',
 'Univariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Univariate, Text ',
 'Sequential ',
 'Text ',
 'Multivariate, Time-Series ',
 'None',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Sequential, Text ',
 'Multivariate, Univariate, Time-Series ',
 'Time-Series, Multivariate ',
 'Multivariate ',
 'Sequential ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Domain-Theory ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series, Text ',
 'Univariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'None',
 'None',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Univariate, Sequential, Time-Series ',
 'Univariate, Sequential, Time-Series ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Univariate, Domain-Theory ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'None',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Text ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Univariate, Sequential, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'None',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series, Domain-Theory ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series, Domain-Theory ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Text ',
 'Multivariate, Text ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'None',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'None',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'None',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Time-Series ',
 'Text ',
 'None',
 'None',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Sequential, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'None',
 'Sequential ',
 'Univariate ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Univariate, Domain-Theory ',
 'Multivariate ',
 'Text ',
 'Sequential ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Text ',
 'Time-Series ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Univariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate ',
 'None',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Univariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Text ',
 'Multivariate, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate, Univariate ',
 'Multivariate, Sequential ',
 'Text ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series, Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series, Text ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Sequential, Time-Series ',
 'Multivariate, Univariate ',
 'Multivariate ',
 'Multivariate, Univariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'None',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate, Time-Series ',
 'Univariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Sequential ',
 'Sequential, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'None',
 'Text ',
 'Text ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate ',
 'Time-Series ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Sequential, Time-Series ',
 'Time-Series ',
 'Multivariate ',
 'Sequential ',
 'Multivariate ',
 'Text ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate, Text ',
 'Multivariate, Time-Series ',
 'Multivariate ',
 'Multivariate ',
 'Multivariate ',
 'Time-Series ',
 'Time-Series ',
 'Multivariate ']

In [144]:
len(datatype)

588

In [116]:
task=[]
for i in range(2,590):        
    task_tags=driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{}]/td[3]/p".format(i))
    
    if(task_tags.text!=' '):
        task.append(task_tags.text)
    else:
        task.append("No Data")

In [128]:
task

['Classification ',
 'Classification ',
 'Classification ',
 'Recommender-Systems ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'No Data',
 'No Data',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'No Data',
 'No Data',
 'No Data',
 'No Data',
 'Classification ',
 'Classification ',
 'Classification ',
 'Function-Learning ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'No Data',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Relational-Learning ',
 'No Data',
 'Classification ',
 'Classification ',
 'Classification ',
 'No Data',
 'No Data',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'No Data',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'No Data',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'No Data',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'No Data',
 'No Data',
 'Classification ',
 'Regression ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'No Data',
 'No Data',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'No Data',
 'No Data',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Classification ',
 'No Data',
 'No Data',
 'No Data',
 'No Data',
 'No Data',
 'Recommender-Systems ',
 'Classification ',
 'Regression, Description ',
 'No Data',
 'No Data',
 'Classification ',
 'Regression ',
 'Classification ',
 'No Data',
 'No Data',
 'No Data',
 'No Data',
 'No Data',
 'No Data',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'No Data',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'No Data',
 'Classification ',
 'Classification ',
 'No Data',
 'No Data',
 'No Data',
 'No Data',
 'No Data',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Causal-Discovery ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Causal-Discovery ',
 'Clustering ',
 'Classification, Clustering ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'No Data',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'No Data',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression, Clustering, Causal-Discovery ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'No Data',
 'Classification ',
 'Regression, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'No Data',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Regression, Clustering ',
 'Classification, Regression ',
 'Regression, Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering, Causa ',
 'Classification, Clustering ',
 'Regression ',
 'Classification ',
 'Regression ',
 'Regression ',
 'No Data',
 'Classification ',
 'No Data',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering, Causal-Discovery ',
 'Classification, Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Classification, Regression ',
 'Classification, Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Regression ',
 'Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Causal-Discovery ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Regression, Clustering, Causal-Discovery ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Clustering, Causal-Discovery ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Causal-Discovery ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Causal-Discovery ',
 'Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Clustering, Causal-Discovery ',
 'Classification, Regression ',
 'Classification, Regression, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Causal-Discovery ',
 'Classification, Clustering ',
 'Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Regression ',
 'Classification, Regression, Clustering ',
 'Clustering ',
 'Classification, Regression ',
 'No Data',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Clustering ',
 'Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Regression ',
 'Clustering ',
 'Classification ',
 'Regression ',
 'Clustering ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Recommendation ',
 'Classification, Regression, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Regression ',
 'Classification, Regression ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Regression ',
 'Clustering ',
 'Classification ',
 'Regression ',
 'Regression, Clustering ',
 'Regression ',
 'Regression ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Regression, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Regression ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Regression ',
 'Classification, Clustering ',
 'Regression ',
 'Regression ',
 'Classification, Regression ',
 'Classification, Clustering, Causal-Discovery ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Clustering ',
 'Regression ',
 'Classification ',
 'Regression ',
 'Classification ',
 'Classification, Regression, Causal-Discovery ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Causal-Discovery ',
 'Clustering ',
 'Regression, Clustering ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Classification, Regression ',
 'Classification, Regression, Clustering ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification, Regression, Clustering ',
 'Regression ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Classification ',
 'Classification, Clustering ',
 'Classification ',
 'Clustering ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Clustering ',
 'Classification, Regression ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Classification, Regression ',
 'Classification, Clustering ',
 'Classification ',
 'Classification ',
 'Classification, Regression, Causal-Discovery ',
 'Classification ',
 'Classification ',
 'Classification ',
 'Regression ',
 'Regression ',
 'Regression ']

In [145]:
len(task)

588

In [130]:
attrtype=[]
for i in range(2,590):        
    attrtype_tags=driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{}]/td[4]/p".format(i))
    
    if(attrtype_tags.text!=' '):
        attrtype.append(attrtype_tags.text)
    else:
        attrtype.append("No Data")

In [139]:
attrtype

['Categorical, Integer, Real ',
 'Categorical, Integer ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical ',
 'Categorical, Real ',
 'Categorical, Integer, Real ',
 'No Data',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Integer ',
 'Real ',
 'Real ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Integer ',
 'No Data',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Real, Integer ',
 'Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical, Integer, Real ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Real ',
 'No Data',
 'No Data',
 'Categorical, Integer, Real ',
 'Real ',
 'Categorical, Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Real ',
 'Real ',
 'Categorical, Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical ',
 'Integer ',
 'Categorical, Integer, Real ',
 'No Data',
 'Integer ',
 'Categorical ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical, Integer, Real ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'No Data',
 'Integer, Real ',
 'Categorical ',
 'Integer ',
 'Integer ',
 'Categorical ',
 'No Data',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Categorical, Integer ',
 'Categorical ',
 'No Data',
 'No Data',
 'Real ',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Categorical ',
 'Integer ',
 'Integer, Real ',
 'Integer, Real ',
 'Categorical ',
 'Integer ',
 'Categorical, Integer ',
 'No Data',
 'No Data',
 'Categorical, Integer ',
 'Categorical ',
 'Categorical, Real ',
 'Categorical ',
 'Categorical, Integer ',
 'Categorical ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Categorical, Integer ',
 'No Data',
 'No Data',
 'Categorical, Real ',
 'Real ',
 'Categorical ',
 'Categorical, Integer ',
 'Categorical, Real ',
 'Real ',
 'No Data',
 'Categorical, Integer, Real ',
 'Integer, Real ',
 'Categorical ',
 'Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Real ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'No Data',
 'No Data',
 'Categorical ',
 'No Data',
 'Categorical, Real ',
 'No Data',
 'Categorical ',
 'Integer ',
 'Real ',
 'Categorical ',
 'No Data',
 'No Data',
 'Categorical, Integer, Real ',
 'Categorical, Integer ',
 'Categorical, Real ',
 'Integer ',
 'Real ',
 'Integer ',
 'Integer ',
 'Categorical ',
 'Real ',
 'Real ',
 'No Data',
 'No Data',
 'Real ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Categorical, Integer ',
 'Real ',
 'Integer ',
 'Integer ',
 'Real ',
 'No Data',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Real ',
 'Categorical ',
 'Real ',
 'Real ',
 'Real ',
 'Categorical, Integer ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'No Data',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Categorical, Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'No Data',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'No Data',
 'Real ',
 'No Data',
 'No Data',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'No Data',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'No Data',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'No Data',
 'No Data',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'No Data',
 'Real ',
 'Integer ',
 'Real ',
 'No Data',
 'No Data',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'No Data',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'No Data',
 'Real ',
 'No Data',
 'No Data',
 'Real ',
 'Real ',
 'Real ',
 'No Data',
 'Real ',
 'Real ',
 'Integer ',
 'No Data',
 'Real ',
 'No Data',
 'Integer ',
 'No Data',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'No Data',
 'No Data',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'No Data',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'No Data',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Categorical ',
 'No Data',
 'Integer, Real ',
 'No Data',
 'No Data',
 'Integer, Real ',
 'Real ',
 'Real ',
 'No Data',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'No Data',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'No Data',
 'Integer ',
 'No Data',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'No Data',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 'No Data',
 'Integer, Real ',
 'No Data',
 'Real ',
 'Real ',
 'No Data',
 'Integer ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'No Data',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'No Data',
 'Integer, Real ',
 'Real ',
 'No Data',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'No Data',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'Real ',
 'No Data',
 'No Data',
 'Integer ',
 'Integer ',
 'Integer ',
 'No Data',
 'Real ',
 'Categorical ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'No Data',
 'Integer, Real ',
 'No Data',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'No Data',
 'No Data',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Integer ',
 'No Data',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Integer ',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'No Data',
 'No Data',
 'No Data',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'No Data',
 'Integer, Real ',
 'No Data',
 'No Data',
 'Integer, Real ',
 'Integer ',
 'No Data',
 'Real ',
 'No Data',
 'Real ',
 'Integer ',
 'No Data',
 'Integer ',
 'Integer, Real ',
 'Integer, Real ',
 'No Data',
 'No Data',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'Real ',
 'Integer ',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'No Data',
 'No Data',
 'No Data',
 'Real ',
 'Real ',
 'Integer, Real ',
 'Real ',
 'No Data',
 'Integer ',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'No Data',
 'Integer ',
 'Real ',
 'No Data',
 'Integer, Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 'No Data',
 'No Data',
 'No Data',
 'Real ',
 'Real ',
 'Real ',
 'Integer, Real ',
 'No Data',
 'Real ',
 'Integer ',
 'Integer, Real ',
 'Integer ',
 'Integer ',
 'No Data',
 'No Data',
 'Real ',
 'No Data',
 'Integer ',
 'Real ',
 'No Data',
 'No Data',
 'Real ',
 'Integer, Real ',
 'Integer ',
 'No Data',
 'No Data',
 'Real ',
 'Integer, Real ',
 'No Data',
 'Real ',
 'Real ',
 'Real ',
 'Real ']

In [146]:
len(attrtype)

588

In [132]:
num_of_instances=[]
for i in range(2,590):        
    num_of_instances_tags=driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{}]/td[5]/p".format(i))
    
    if(num_of_instances_tags.text!=' '):
        num_of_instances.append(num_of_instances_tags.text)
    else:
        num_of_instances.append("No Data")

In [140]:
num_of_instances

['4177 ',
 '48842 ',
 '798 ',
 '37711 ',
 '452 ',
 '6000 ',
 '226 ',
 '226 ',
 '398 ',
 '205 ',
 '294 ',
 '625 ',
 '16 ',
 '286 ',
 '699 ',
 '198 ',
 '569 ',
 '108 ',
 '1728 ',
 '48842 ',
 'No Data',
 '3196 ',
 '28056 ',
 'No Data',
 '100 ',
 '67557 ',
 '690 ',
 '125 ',
 '209 ',
 '1473 ',
 '581012 ',
 '512 ',
 '366 ',
 'No Data',
 'No Data',
 'No Data',
 'No Data',
 '132 ',
 '336 ',
 '194 ',
 '352 ',
 '214 ',
 '306 ',
 '160 ',
 '303 ',
 '155 ',
 '368 ',
 'No Data',
 '2310 ',
 '3279 ',
 '351 ',
 '150 ',
 '7797 ',
 '104 ',
 '57 ',
 'No Data',
 '24 ',
 '20000 ',
 '345 ',
 'No Data',
 '32 ',
 '148 ',
 '209 ',
 '528 ',
 'No Data',
 '106 ',
 '128 ',
 '3190 ',
 '432 ',
 '202 ',
 '2000 ',
 '8124 ',
 '476 ',
 '6598 ',
 '12960 ',
 'No Data',
 '5473 ',
 '5620 ',
 '10992 ',
 '90 ',
 '339 ',
 'No Data',
 'No Data',
 'No Data',
 '167 ',
 '15 ',
 '1389 ',
 '307 ',
 '47 ',
 '23 ',
 '531 ',
 '4601 ',
 '267 ',
 '267 ',
 '76 ',
 'No Data',
 '1000 ',
 '151 ',
 '958 ',
 '7200 ',
 '10 ',
 '285 ',
 '435 ',
 '527 ',
 '5000 ',
 '5000 ',
 '178 ',
 '1484 ',
 '101 ',
 'No Data',
 '20000 ',
 '6650 ',
 '2565 ',
 '2458285 ',
 '299285 ',
 '340 ',
 '68040 ',
 'No Data',
 '122 ',
 '178080 ',
 '50672 ',
 '640 ',
 '9000 ',
 '10104 ',
 '256932 ',
 '640 ',
 '191779 ',
 '4000000 ',
 'No Data',
 '10000 ',
 '989818 ',
 '129000 ',
 'No Data',
 '100000 ',
 '21578 ',
 '463 ',
 '600 ',
 '332 ',
 'No Data',
 'No Data',
 '690 ',
 '1000 ',
 '270 ',
 '6435 ',
 '2310 ',
 '58000 ',
 '946 ',
 '20008 ',
 '208 ',
 '528 ',
 'No Data',
 'No Data',
 '1024 ',
 '10080 ',
 '50400 ',
 '1025010 ',
 '19020 ',
 '1364 ',
 '961 ',
 '517 ',
 '200 ',
 '8000000 ',
 '1030 ',
 '606 ',
 '900 ',
 '2600 ',
 '1950 ',
 '13500 ',
 '4400 ',
 '2536 ',
 '300 ',
 '197 ',
 '2858 ',
 '748 ',
 '11640 ',
 '1593 ',
 '1567 ',
 '22632 ',
 '360 ',
 '103 ',
 '1994 ',
 '120 ',
 '4898 ',
 '2396130 ',
 '16772 ',
 '5875 ',
 '503 ',
 '51 ',
 '106 ',
 '2126 ',
 '5456 ',
 '8800 ',
 '164860 ',
 'No Data',
 '1941 ',
 '130065 ',
 '515345 ',
 '440 ',
 'No Data',
 '53500 ',
 '8235 ',
 'No Data',
 '5749132 ',
 '2215 ',
 '310 ',
 '10000 ',
 '3000 ',
 '1500 ',
 '30000 ',
 '2500 ',
 '4143 ',
 '64 ',
 '53414 ',
 '65554 ',
 '45211 ',
 '1138562 ',
 '13910 ',
 '583 ',
 '2551 ',
 '34465 ',
 '5574 ',
 '245057 ',
 '182 ',
 '3850505 ',
 '138 ',
 '1080 ',
 '2075259 ',
 '210 ',
 '115 ',
 '3960456 ',
 'No Data',
 '10299 ',
 '1600 ',
 '768 ',
 '308 ',
 '100 ',
 '237 ',
 '434874 ',
 '536 ',
 '140000 ',
 '6118 ',
 '165632 ',
 '18000 ',
 '540 ',
 '931 ',
 '1055 ',
 '100 ',
 '9120 ',
 '403 ',
 '111740 ',
 '10421 ',
 '5820 ',
 '403 ',
 '14980 ',
 '45730 ',
 '2584 ',
 '1372 ',
 '306 ',
 '120000 ',
 '13910 ',
 '2747 ',
 '3395 ',
 '39242 ',
 '4137 ',
 '17389 ',
 '51 ',
 '470 ',
 '132 ',
 '5000000 ',
 '11000000 ',
 '250 ',
 '126 ',
 'No Data',
 '4889 ',
 'No Data',
 'No Data',
 '340 ',
 '501 ',
 '45781 ',
 '1503 ',
 '440 ',
 '2000 ',
 '9568 ',
 '168 ',
 '100000 ',
 '5665 ',
 '79 ',
 '127 ',
 '1040 ',
 '9900 ',
 '560 ',
 '60021 ',
 '1419 ',
 '101 ',
 '399 ',
 '58 ',
 '180 ',
 '21048 ',
 'No Data',
 '750 ',
 '3000 ',
 '150 ',
 '1059 ',
 '11934 ',
 '27965 ',
 '216 ',
 '120 ',
 '649 ',
 '370 ',
 '4178504 ',
 '221579 ',
 '10800 ',
 '58509 ',
 '129685 ',
 '2456 ',
 '2921 ',
 '1151 ',
 '6590 ',
 '3000 ',
 '39797 ',
 '326 ',
 '913 ',
 '168286 ',
 '400 ',
 '314080 ',
 '637 ',
 '1710671 ',
 '12000 ',
 '10929 ',
 '1080 ',
 '40000 ',
 '43930257 ',
 '230318 ',
 '10500000 ',
 '13197 ',
 'No Data',
 '30000 ',
 '324 ',
 '541909 ',
 '11164866 ',
 '163 ',
 '373 ',
 '20560 ',
 '40 ',
 '422937 ',
 '9358 ',
 '640 ',
 '919438 ',
 '40949 ',
 '5744 ',
 '10503 ',
 '42240 ',
 '102944 ',
 '500 ',
 '9782222 ',
 '11463 ',
 '17898 ',
 '1885 ',
 '19735 ',
 '1540 ',
 '4007 ',
 '153540 ',
 '606 ',
 '1353 ',
 '1956 ',
 '43824 ',
 '3942 ',
 '858 ',
 '287 ',
 '17764280 ',
 '106574 ',
 '9358 ',
 '11500 ',
 '92000 ',
 '315 ',
 '78095 ',
 '130 ',
 '74 ',
 '52854 ',
 '77 ',
 '811 ',
 '504 ',
 '401 ',
 '2856 ',
 '10546 ',
 '801 ',
 '1540 ',
 '1451 ',
 '1075 ',
 '78095 ',
 '7195 ',
 '3600 ',
 '76 ',
 '60 ',
 '405 ',
 '303 ',
 '303 ',
 '107888 ',
 '76000 ',
 '10000 ',
 '180 ',
 '745000 ',
 '12234 ',
 '292 ',
 '104 ',
 '60000 ',
 '2000 ',
 '165 ',
 '217 ',
 '1175 ',
 '704 ',
 '75128 ',
 '90 ',
 '90 ',
 '50 ',
 '71 ',
 '93239 ',
 '540 ',
 '105 ',
 '6611 ',
 '15 ',
 '372 ',
 '58000 ',
 '4960 ',
 '241600 ',
 '130000 ',
 '7062606 ',
 '740 ',
 '70 ',
 '2205 ',
 '10721 ',
 '640 ',
 '1000 ',
 '116 ',
 '1672 ',
 '322 ',
 '93600 ',
 '3060 ',
 '5879 ',
 '9200 ',
 '20000 ',
 '20867 ',
 'No Data',
 '4143 ',
 '215063 ',
 '6000000 ',
 '21263 ',
 '63000000 ',
 '10190 ',
 '300 ',
 '12330 ',
 '5180 ',
 '756 ',
 '10000 ',
 '80 ',
 '1184 ',
 '1047 ',
 '777 ',
 '249 ',
 '414 ',
 'No Data',
 '143 ',
 '7840 ',
 '30000 ',
 '35717 ',
 '135 ',
 '980 ',
 '5456 ',
 '120 ',
 '4095000 ',
 '7051 ',
 '240 ',
 '48204 ',
 '260000 ',
 '288000 ',
 '8300000 ',
 '125 ',
 '170 ',
 '141712 ',
 '3916 ',
 '6262 ',
 '420768 ',
 '1067371 ',
 '1385 ',
 '908 ',
 '546 ',
 '13956534 ',
 '15630426 ',
 '8992 ',
 '1687 ',
 '779 ',
 '1056 ',
 '590 ',
 '21643 ',
 '7750 ',
 '14057567 ',
 '27170754 ',
 '597 ',
 '329 ',
 '299 ',
 '20000 ',
 '26136 ',
 '1000 ',
 '399 ',
 '24017 ',
 '325834 ',
 '2916697 ',
 '22470 ',
 '189 ',
 '520 ',
 '826 ',
 '2279 ',
 '28764 ',
 '7107 ',
 '288000 ',
 '9800 ',
 '4760 ',
 '72 ',
 '1450 ',
 '170 ',
 '1984 ',
 '2955 ',
 '65532 ',
 '65919 ',
 '2111 ',
 '3810 ',
 '18 ',
 '244 ',
 '104 ',
 '139 ',
 '360177 ',
 '36733 ',
 '4480 ',
 '165474 ',
 '1985 ',
 '10000 ',
 '232 ',
 '150 ',
 '11 ',
 '14057567 ',
 '8760 ',
 '48 ',
 '6321 ',
 '3150 ',
 '17256 ',
 '187 ',
 '399 ',
 '14 ',
 '467 ',
 '597 ',
 '23700 ',
 '615 ',
 '6819 ',
 '1000 ',
 'No Data',
 '2633 ',
 '200 ',
 '13028 ',
 '800 ',
 '1700 ',
 '521 ',
 '120000 ',
 '666 ',
 '88 ',
 '200 ',
 '2279 ',
 '23570 ',
 '10000 ',
 '37700 ',
 '1850 ',
 '11 ',
 '147270 ',
 '3150 ',
 '17256 ',
 '597 ',
 '7624 ',
 '314 ',
 '1197 ',
 '70 ',
 '7624 ',
 '26737 ',
 '10000 ',
 '13611 ',
 '12684 ',
 '48 ',
 '731 ',
 '731 ',
 '557 ']

In [147]:
len(num_of_instances)

588

In [134]:
num_of_attributes=[]
for i in range(2,590):        
    num_of_attributes_tags=driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{}]/td[6]/p".format(i))
    
    if(num_of_attributes_tags.text!=' '):
        num_of_attributes.append(num_of_attributes_tags.text)
    else:
        num_of_attributes.append("No Data")

In [141]:
num_of_attributes

['8 ',
 '14 ',
 '38 ',
 '294 ',
 '279 ',
 '7 ',
 'No Data',
 '69 ',
 '8 ',
 '26 ',
 '1 ',
 '4 ',
 '4 ',
 '9 ',
 '10 ',
 '34 ',
 '32 ',
 '13 ',
 '6 ',
 '14 ',
 '22 ',
 '36 ',
 '6 ',
 'No Data',
 '6 ',
 '42 ',
 '15 ',
 'No Data',
 '9 ',
 '9 ',
 '54 ',
 '39 ',
 '33 ',
 '20 ',
 'No Data',
 'No Data',
 'No Data',
 '12 ',
 '8 ',
 '30 ',
 'No Data',
 '10 ',
 '3 ',
 '5 ',
 '75 ',
 '19 ',
 '27 ',
 'No Data',
 '19 ',
 '1558 ',
 '34 ',
 '4 ',
 '617 ',
 '12 ',
 '16 ',
 '7 ',
 '4 ',
 '16 ',
 '7 ',
 'No Data',
 '56 ',
 '18 ',
 '8 ',
 '22 ',
 'No Data',
 '58 ',
 'No Data',
 '61 ',
 '7 ',
 'No Data',
 '649 ',
 '22 ',
 '168 ',
 '168 ',
 '8 ',
 'No Data',
 '10 ',
 '64 ',
 '16 ',
 '8 ',
 '17 ',
 'No Data',
 'No Data',
 '72 ',
 '4 ',
 '6 ',
 '10 ',
 '35 ',
 '35 ',
 '4 ',
 '102 ',
 '57 ',
 '22 ',
 '44 ',
 '45 ',
 'No Data',
 'No Data',
 '5 ',
 '9 ',
 '21 ',
 '32 ',
 '17 ',
 '16 ',
 '38 ',
 '21 ',
 '40 ',
 '13 ',
 '8 ',
 '17 ',
 'No Data',
 'No Data',
 '15 ',
 '22 ',
 '68 ',
 '40 ',
 '17 ',
 '89 ',
 'No Data',
 '4 ',
 '12 ',
 'No Data',
 'No Data',
 '86 ',
 '72 ',
 '61 ',
 '12 ',
 '481 ',
 '42 ',
 'No Data',
 'No Data',
 'No Data',
 'No Data',
 'No Data',
 'No Data',
 '5 ',
 '90 ',
 'No Data',
 '5 ',
 'No Data',
 'No Data',
 '14 ',
 '20 ',
 '13 ',
 '36 ',
 '19 ',
 '9 ',
 '18 ',
 '4 ',
 '60 ',
 '10 ',
 'No Data',
 'No Data',
 '10 ',
 '4 ',
 '3 ',
 '11 ',
 '11 ',
 'No Data',
 '6 ',
 '13 ',
 'No Data',
 '100000 ',
 '9 ',
 '101 ',
 '10000 ',
 '20000 ',
 '100000 ',
 '5000 ',
 '500 ',
 '73 ',
 '43 ',
 '23 ',
 '3 ',
 '5 ',
 'No Data',
 '256 ',
 '591 ',
 '70 ',
 '91 ',
 '10 ',
 '128 ',
 '6 ',
 '12 ',
 '3231961 ',
 '5409 ',
 '26 ',
 'No Data',
 'No Data',
 '10 ',
 '23 ',
 '24 ',
 '13 ',
 '8 ',
 'No Data',
 '27 ',
 '50 ',
 '90 ',
 '138672 ',
 'No Data',
 '386 ',
 'No Data',
 'No Data',
 '12 ',
 '147 ',
 '6 ',
 '8 ',
 '27 ',
 '10000 ',
 '20000 ',
 '10000 ',
 '54877 ',
 '4702 ',
 '24 ',
 '29 ',
 '17 ',
 '3 ',
 '128 ',
 '10 ',
 '242 ',
 '120 ',
 'No Data',
 '4 ',
 '13 ',
 '52 ',
 '47 ',
 '857 ',
 '9 ',
 '7 ',
 '200 ',
 '4 ',
 'No Data',
 '561 ',
 '64 ',
 '8 ',
 '7 ',
 '10 ',
 '9 ',
 '4 ',
 '8 ',
 '77 ',
 '51 ',
 '18 ',
 '1950000 ',
 '18 ',
 '1300 ',
 '41 ',
 '6 ',
 '5625 ',
 '5 ',
 'No Data',
 '7 ',
 '33 ',
 '5 ',
 '15 ',
 '9 ',
 '19 ',
 '5 ',
 '5 ',
 '1000000 ',
 '129 ',
 'No Data',
 '20 ',
 '152 ',
 '24 ',
 '16 ',
 '35 ',
 '17 ',
 '5 ',
 '18 ',
 '28 ',
 '7 ',
 '309 ',
 '3 ',
 '6 ',
 'No Data',
 'No Data',
 '16 ',
 '13 ',
 '5 ',
 '6 ',
 '8 ',
 '2 ',
 '4 ',
 '148 ',
 '55 ',
 '17 ',
 '8 ',
 '42 ',
 '26 ',
 '50 ',
 '2 ',
 '281 ',
 '120 ',
 'No Data',
 '6 ',
 '120432 ',
 '150000 ',
 '529 ',
 'No Data',
 '16 ',
 '2500 ',
 '5 ',
 '68 ',
 '16 ',
 '100 ',
 '216 ',
 '23 ',
 '33 ',
 '140256 ',
 '19 ',
 '20 ',
 '20 ',
 '49 ',
 '12 ',
 '30 ',
 '5232 ',
 '20 ',
 '1 ',
 'No Data',
 '61 ',
 '27 ',
 '53 ',
 '11 ',
 '25 ',
 '0 ',
 '20 ',
 '9 ',
 '3 ',
 '561 ',
 '82 ',
 '13 ',
 '16 ',
 '13 ',
 '28 ',
 '4 ',
 'No Data',
 '24 ',
 '34 ',
 '8 ',
 '128 ',
 '15 ',
 '513 ',
 '7 ',
 '7 ',
 '5 ',
 '15 ',
 '480000 ',
 '11 ',
 '54 ',
 '561 ',
 '64 ',
 '6 ',
 '116 ',
 '19 ',
 'No Data',
 '5812 ',
 '9 ',
 '32 ',
 '29 ',
 '67 ',
 'No Data',
 '25 ',
 '6400 ',
 '10 ',
 '5 ',
 '13 ',
 '98 ',
 '36 ',
 '69 ',
 '2158859 ',
 '518 ',
 '15 ',
 '179 ',
 'No Data',
 '12 ',
 '38 ',
 '65 ',
 '102 ',
 '86 ',
 '7 ',
 '53 ',
 '20 ',
 '1 ',
 '71 ',
 '29 ',
 '20531 ',
 '65 ',
 '3 ',
 '22 ',
 '38 ',
 '22 ',
 '4814 ',
 '698 ',
 '13 ',
 '10 ',
 '59 ',
 '56 ',
 '482 ',
 '171 ',
 '5 ',
 '500 ',
 '411 ',
 '8519 ',
 '21 ',
 '21 ',
 '171 ',
 '7 ',
 '49 ',
 '12 ',
 '3 ',
 '21 ',
 '9 ',
 '8 ',
 '7 ',
 '2 ',
 '11 ',
 '11 ',
 '173 ',
 '5 ',
 '15 ',
 '3 ',
 '105 ',
 '25000 ',
 'No Data',
 '18 ',
 '21000 ',
 '115 ',
 '21 ',
 '206 ',
 '43680 ',
 '8 ',
 '10 ',
 '59 ',
 '10 ',
 '5 ',
 '5 ',
 '1000 ',
 '138 ',
 'No Data',
 '16 ',
 '2 ',
 '10 ',
 'No Data',
 '8 ',
 '6 ',
 '129 ',
 '81 ',
 '12 ',
 '6 ',
 '22 ',
 '18 ',
 '9 ',
 '754 ',
 '14 ',
 '5 ',
 'No Data',
 'No Data',
 '18 ',
 '7 ',
 '7 ',
 'No Data',
 '7 ',
 '5 ',
 '6 ',
 '4 ',
 '18 ',
 '11 ',
 '25 ',
 'No Data',
 '20 ',
 '12 ',
 '46 ',
 '9 ',
 '8 ',
 '49 ',
 '11 ',
 '8 ',
 '54 ',
 '36 ',
 '3916 ',
 '710 ',
 '18 ',
 '8 ',
 '29 ',
 '7 ',
 '9 ',
 '37 ',
 '6 ',
 '1024 ',
 '1024 ',
 '14 ',
 '7 ',
 '8265 ',
 '29 ',
 '25 ',
 '3 ',
 '115 ',
 '1 ',
 '12 ',
 '13 ',
 '200000 ',
 '6 ',
 '21 ',
 '4 ',
 '2400 ',
 '175 ',
 '10 ',
 '4714 ',
 '23 ',
 '17 ',
 '2 ',
 '9 ',
 '8 ',
 '280 ',
 '49 ',
 '3 ',
 '14 ',
 '19 ',
 'No Data',
 '54 ',
 '8 ',
 '1087 ',
 '12 ',
 '3 ',
 '17 ',
 '8 ',
 '9 ',
 '12 ',
 '1656 ',
 '6 ',
 '2 ',
 '11 ',
 '533 ',
 '14 ',
 '84 ',
 '22 ',
 '16 ',
 '52 ',
 '19 ',
 '3 ',
 '14 ',
 '321 ',
 '13 ',
 '13 ',
 '55 ',
 '39 ',
 '4 ',
 '7 ',
 '79 ',
 '1 ',
 'No Data',
 '14 ',
 '96 ',
 '21 ',
 'No Data',
 '5 ',
 '2 ',
 '69 ',
 '9 ',
 '124 ',
 '20 ',
 '25 ',
 '11 ',
 '19 ',
 '9 ',
 '9 ',
 '5 ',
 '7 ',
 '4006 ',
 '2 ',
 '19 ',
 '4 ',
 '13 ',
 '55 ',
 '1 ',
 '7842 ',
 '15 ',
 '15 ',
 '70 ',
 '7842 ',
 '4 ',
 '14 ',
 '17 ',
 '23 ',
 '321 ',
 '1068 ',
 '1068 ',
 '5 ']

In [148]:
len(num_of_attributes)

588

In [136]:
year=[]
for i in range(2,590):        
    year_tags=driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{}]/td[7]/p".format(i))
    
    if(year_tags.text!=' '):
        year.append(year_tags.text)
    else:
        year.append("No Data")

In [142]:
year

['1995 ',
 '1996 ',
 'No Data',
 '1998 ',
 '1998 ',
 '1992 ',
 '1987 ',
 '1992 ',
 '1993 ',
 '1987 ',
 '1994 ',
 '1994 ',
 'No Data',
 '1988 ',
 '1992 ',
 '1995 ',
 '1995 ',
 '1990 ',
 '1997 ',
 '1996 ',
 '1988 ',
 '1989 ',
 '1994 ',
 'No Data',
 'No Data',
 '1995 ',
 'No Data',
 '1992 ',
 '1987 ',
 '1997 ',
 '1998 ',
 '1995 ',
 '1998 ',
 'No Data',
 'No Data',
 '1994 ',
 'No Data',
 '1989 ',
 '1996 ',
 '1990 ',
 '1990 ',
 '1987 ',
 '1999 ',
 '1989 ',
 '1988 ',
 '1988 ',
 '1989 ',
 'No Data',
 '1990 ',
 '1998 ',
 '1989 ',
 '1988 ',
 '1994 ',
 '1990 ',
 '1988 ',
 '1988 ',
 '1990 ',
 '1991 ',
 '1990 ',
 'No Data',
 '1992 ',
 '1988 ',
 '1990 ',
 '1996 ',
 '1995 ',
 '1990 ',
 'No Data',
 '1992 ',
 '1992 ',
 '1994 ',
 'No Data',
 '1987 ',
 '1994 ',
 '1994 ',
 '1997 ',
 '1991 ',
 '1995 ',
 '1998 ',
 '1998 ',
 '1993 ',
 '1988 ',
 'No Data',
 'No Data',
 '1992 ',
 '1993 ',
 '1988 ',
 '1989 ',
 '1988 ',
 '1987 ',
 '1993 ',
 '1988 ',
 '1999 ',
 '2001 ',
 '2001 ',
 'No Data',
 '1992 ',
 '1993 ',
 '1997 ',
 '1991 ',
 '1987 ',
 '1994 ',
 '1988 ',
 '1987 ',
 '1993 ',
 '1988 ',
 '1988 ',
 '1991 ',
 '1996 ',
 '1990 ',
 'No Data',
 '1999 ',
 '1999 ',
 '2002 ',
 'No Data',
 '2000 ',
 '1999 ',
 '1999 ',
 '2001 ',
 '1999 ',
 '1999 ',
 '2000 ',
 '1999 ',
 '2000 ',
 '1999 ',
 '1999 ',
 'No Data',
 '1998 ',
 '1999 ',
 '2001 ',
 '1999 ',
 'No Data',
 '2003 ',
 '1999 ',
 '1999 ',
 '1997 ',
 '1999 ',
 '1999 ',
 '1998 ',
 'No Data',
 'No Data',
 'No Data',
 '1994 ',
 'No Data',
 '1993 ',
 '1990 ',
 'No Data',
 'No Data',
 'No Data',
 'No Data',
 'No Data',
 'No Data',
 'No Data',
 '1989 ',
 '2006 ',
 '2006 ',
 '2007 ',
 '2007 ',
 '2007 ',
 '2007 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2007 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2009 ',
 '2008 ',
 '2008 ',
 '2008 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2009 ',
 '2010 ',
 '2009 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2010 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2012 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2014 ',
 '2013 ',
 '2013 ',
 '2013 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2013 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2014 ',
 '2015 ',
 '2014 ',
 '2014 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2014 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2016 ',
 '2016 ',
 '2015 ',
 '2016 ',
 '2016 ',
 '2015 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2018 ',
 '2018 ',
 '2016 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2019 ',
 '2019 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2021 ',
 '2018 ',
 '2018 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2019 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2020 ',
 '2021 ',
 '2021 ',
 '2021 ']

In [149]:
len(year)

588

In [150]:
ML_Repository=pd.DataFrame({})
ML_Repository["Dataset name"]=name
ML_Repository["Data type"]=datatype
ML_Repository["Task"]=task
ML_Repository["Attribute type"]=attrtype
ML_Repository["No of instances"]=num_of_instances
ML_Repository["No of attribute"]=num_of_attributes
ML_Repository["Year"]=year

In [151]:
ML_Repository

,Dataset name,Data type,Task,Attribute type,No of instances,No of attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,No Data
3,Anonymous Microsoft Web Data,None,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,No Data,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021